// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An API resource in the API Hub.
public struct Api: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the API resource in the API Hub.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/apis/{api}`
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the API resource.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the API resource.
  public var description: Swift.String = Swift.String()

  /// Optional. The documentation for the API resource.
  public var documentation: Documentation? = nil

  /// Optional. Owner details for the API resource.
  public var owner: Owner? = nil

  /// Output only. The list of versions present in an API resource.
  /// Note: An API resource can be associated with more than 1 version.
  /// Format is
  /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}`
  public var versions: [Swift.String] = []

  /// Output only. The time at which the API resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the API resource was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The target users for the API.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-target-user`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var targetUser: AttributeValues? = nil

  /// Optional. The team owning the API.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-team`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var team: AttributeValues? = nil

  /// Optional. The business unit owning the API.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-business-unit`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var businessUnit: AttributeValues? = nil

  /// Optional. The maturity level of the API.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-maturity-level`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var maturityLevel: AttributeValues? = nil

  /// Optional. The list of user defined attributes associated with the API
  /// resource. The key is the attribute name. It will be of the format:
  /// `projects/{project}/locations/{location}/attributes/{attribute}`.
  /// The value is the attribute values associated with the resource.
  public var attributes: [Swift.String: AttributeValues] = [:]

  /// Optional. The style of the API.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-api-style`
  /// attribute.
  /// The number of values for this attribute will be based on the
  /// cardinality of the attribute. The same can be retrieved via GetAttribute
  /// API. All values should be from the list of allowed values defined for the
  /// attribute.
  public var apiStyle: AttributeValues? = nil

  /// Optional. The selected version for an API resource.
  /// This can be used when special handling is needed on client side for
  /// particular version of the API. Format is
  /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}`
  public var selectedVersion: Swift.String = Swift.String()

  /// Optional. The api requirement doc associated with the API resource.
  /// Carinality is 1 for this attribute. This maps to the following system
  /// defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-api-requirements`
  /// attribute. The value of the attribute should be a proper URI, and in case
  /// of Cloud Storage URI, it should point to a Cloud Storage object,
  /// not a directory.
  public var apiRequirements: AttributeValues? = nil

  /// Optional. Fingerprint of the API resource.
  public var fingerprint: Swift.String = Swift.String()

  /// Output only. The list of sources and metadata from the sources of the API
  /// resource.
  public var sourceMetadata: [SourceMetadata] = []

  /// Optional. The api functional requirements associated with the API resource.
  /// Carinality is 1 for this attribute.
  /// This maps to the following system defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-api-functional-requirements`
  /// attribute. The value of the attribute should be a proper URI, and in case
  /// of Cloud Storage URI, it should point to a Cloud Storage object,
  /// not a directory.
  public var apiFunctionalRequirements: AttributeValues? = nil

  /// Optional. The api technical requirements associated with the API resource.
  /// Carinality is 1 for this attribute. This maps to the following system
  /// defined attribute:
  /// `projects/{project}/locations/{location}/attributes/system-api-technical-requirements`
  /// attribute. The value of the attribute should be a proper URI, and in case
  /// of Cloud Storage URI, it should point to a Cloud Storage object,
  /// not a directory.
  public var apiTechnicalRequirements: AttributeValues? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Api`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Api().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let documentation = CodingKeys(stringValue: "documentation")
    static let owner = CodingKeys(stringValue: "owner")
    static let versions = CodingKeys(stringValue: "versions")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let targetUser = CodingKeys(stringValue: "targetUser")
    static let team = CodingKeys(stringValue: "team")
    static let businessUnit = CodingKeys(stringValue: "businessUnit")
    static let maturityLevel = CodingKeys(stringValue: "maturityLevel")
    static let attributes = CodingKeys(stringValue: "attributes")
    static let apiStyle = CodingKeys(stringValue: "apiStyle")
    static let selectedVersion = CodingKeys(stringValue: "selectedVersion")
    static let apiRequirements = CodingKeys(stringValue: "apiRequirements")
    static let fingerprint = CodingKeys(stringValue: "fingerprint")
    static let sourceMetadata = CodingKeys(stringValue: "sourceMetadata")
    static let apiFunctionalRequirements = CodingKeys(stringValue: "apiFunctionalRequirements")
    static let apiTechnicalRequirements = CodingKeys(stringValue: "apiTechnicalRequirements")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "documentation",
      "owner",
      "versions",
      "createTime",
      "updateTime",
      "targetUser",
      "team",
      "businessUnit",
      "maturityLevel",
      "attributes",
      "apiStyle",
      "selectedVersion",
      "apiRequirements",
      "fingerprint",
      "sourceMetadata",
      "apiFunctionalRequirements",
      "apiTechnicalRequirements",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.documentation = try container.decodeIfPresent(Documentation.self, forKey: .documentation)
    self.owner = try container.decodeIfPresent(Owner.self, forKey: .owner)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .versions) {
      self.versions = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.targetUser = try container.decodeIfPresent(AttributeValues.self, forKey: .targetUser)
    self.team = try container.decodeIfPresent(AttributeValues.self, forKey: .team)
    self.businessUnit = try container.decodeIfPresent(AttributeValues.self, forKey: .businessUnit)
    self.maturityLevel = try container.decodeIfPresent(AttributeValues.self, forKey: .maturityLevel)
    if let value = try container.decodeIfPresent(
      [Swift.String: AttributeValues].self, forKey: .attributes)
    {
      self.attributes = value
    }
    self.apiStyle = try container.decodeIfPresent(AttributeValues.self, forKey: .apiStyle)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectedVersion) {
      self.selectedVersion = value
    }
    self.apiRequirements = try container.decodeIfPresent(
      AttributeValues.self, forKey: .apiRequirements)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fingerprint) {
      self.fingerprint = value
    }
    if let value = try container.decodeIfPresent([SourceMetadata].self, forKey: .sourceMetadata) {
      self.sourceMetadata = value
    }
    self.apiFunctionalRequirements = try container.decodeIfPresent(
      AttributeValues.self, forKey: .apiFunctionalRequirements)
    self.apiTechnicalRequirements = try container.decodeIfPresent(
      AttributeValues.self, forKey: .apiTechnicalRequirements)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.documentation, forKey: .documentation)
    try container.encodeIfPresent(self.owner, forKey: .owner)
    try container.encode(self.versions, forKey: .versions)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.targetUser, forKey: .targetUser)
    try container.encodeIfPresent(self.team, forKey: .team)
    try container.encodeIfPresent(self.businessUnit, forKey: .businessUnit)
    try container.encodeIfPresent(self.maturityLevel, forKey: .maturityLevel)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encodeIfPresent(self.apiStyle, forKey: .apiStyle)
    try container.encode(self.selectedVersion, forKey: .selectedVersion)
    try container.encodeIfPresent(self.apiRequirements, forKey: .apiRequirements)
    try container.encode(self.fingerprint, forKey: .fingerprint)
    try container.encode(self.sourceMetadata, forKey: .sourceMetadata)
    try container.encodeIfPresent(
      self.apiFunctionalRequirements, forKey: .apiFunctionalRequirements)
    try container.encodeIfPresent(self.apiTechnicalRequirements, forKey: .apiTechnicalRequirements)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Api"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
