// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ApiHubDiscoveryRetry: ApiHubDiscoveryStub {
    let inner: any ApiHubDiscoveryStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ApiHubDiscoveryStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listDiscoveredApiObservations(
      request: ListDiscoveredApiObservationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDiscoveredApiObservationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse
          in
          return try await self.inner.listDiscoveredApiObservations(request: r, options: o)
        })
    }

    public func getDiscoveredApiObservation(
      request: GetDiscoveredApiObservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.DiscoveredApiObservation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDiscoveredApiObservationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.DiscoveredApiObservation
          in
          return try await self.inner.getDiscoveredApiObservation(request: r, options: o)
        })
    }

    public func listDiscoveredApiOperations(
      request: ListDiscoveredApiOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDiscoveredApiOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse
          in
          return try await self.inner.listDiscoveredApiOperations(request: r, options: o)
        })
    }

    public func getDiscoveredApiOperation(
      request: GetDiscoveredApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.DiscoveredApiOperation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDiscoveredApiOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.DiscoveredApiOperation
          in
          return try await self.inner.getDiscoveredApiOperation(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
