// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// This service exposes methods used to manage DiscoveredApiObservations
/// and DiscoveredApiOperations.
///
/// @Snippet(path: "ApiHubDiscoveryQuickstart")
public final class ApiHubDiscoveryClient: Clients.ApiHubDiscoveryProtocol, Sendable {
  let inner: any Clients.ApiHubDiscoveryStub

  /// Creates a new `ApiHubDiscoveryClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiHubDiscoveryStub = try Clients.ApiHubDiscoveryTransport(options)
    inner = Clients.ApiHubDiscoveryRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiHubDiscoveryLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists all the DiscoveredAPIObservations in a given project and location.
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListDiscoveredApiObservations")
  public func listDiscoveredApiObservations(
    request: ListDiscoveredApiObservationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse {
    try await self.inner.listDiscoveredApiObservations(request: request, options: options)
  }

  /// Gets a DiscoveredAPIObservation in a given project, location and
  /// ApiObservation.
  ///
  /// @Snippet(path: "ApiHubDiscovery_GetDiscoveredApiObservation")
  public func getDiscoveredApiObservation(
    request: GetDiscoveredApiObservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.DiscoveredApiObservation {
    try await self.inner.getDiscoveredApiObservation(request: request, options: options)
  }

  /// Lists all the DiscoveredAPIOperations in a given project, location and
  /// ApiObservation.
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListDiscoveredApiOperations")
  public func listDiscoveredApiOperations(
    request: ListDiscoveredApiOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse {
    try await self.inner.listDiscoveredApiOperations(request: request, options: options)
  }

  /// Gets a DiscoveredAPIOperation in a given project, location,
  /// ApiObservation and ApiOperation.
  ///
  /// @Snippet(path: "ApiHubDiscovery_GetDiscoveredApiOperation")
  public func getDiscoveredApiOperation(
    request: GetDiscoveredApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.DiscoveredApiOperation {
    try await self.inner.getDiscoveredApiOperation(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ApiHubDiscovery_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDiscovery_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDiscovery_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDiscovery_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiHubDiscoveryClient`.
  ///
  /// To mock `ApiHubDiscoveryClient` change your functions to receive
  /// `some ApiHubDiscoveryProtocol` or `any ApiHubDiscoveryProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiHubDiscoveryProtocol: Sendable {
    /// See `ApiHubDiscoveryClient.listDiscoveredApiObservations`.
    func listDiscoveredApiObservations(
      request: ListDiscoveredApiObservationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse

    /// See `ApiHubDiscoveryClient.getDiscoveredApiObservation`.
    func getDiscoveredApiObservation(
      request: GetDiscoveredApiObservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.DiscoveredApiObservation

    /// See `ApiHubDiscoveryClient.listDiscoveredApiOperations`.
    func listDiscoveredApiOperations(
      request: ListDiscoveredApiOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse

    /// See `ApiHubDiscoveryClient.getDiscoveredApiOperation`.
    func getDiscoveredApiOperation(
      request: GetDiscoveredApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.DiscoveredApiOperation

    /// See `ApiHubDiscoveryClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ApiHubDiscoveryClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ApiHubDiscoveryClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ApiHubDiscoveryClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubDiscoveryClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ApiHubDiscoveryProtocol {
  public func listDiscoveredApiObservations(request: ListDiscoveredApiObservationsRequest)
    async throws -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse
  {
    try await self.listDiscoveredApiObservations(request: request, options: .init())
  }

  public func listDiscoveredApiObservations(
    request: ListDiscoveredApiObservationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDiscoveredApiObservationsByItems(
    request: ListDiscoveredApiObservationsRequest
  ) -> any AsyncSequence<DiscoveredApiObservation, Swift.Error> & Sendable {
    self.listDiscoveredApiObservationsByItems(request: request, options: .init())
  }

  /// Lists all the DiscoveredAPIObservations in a given project and location.
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListDiscoveredApiObservations")
  public func listDiscoveredApiObservationsByItems(
    request: ListDiscoveredApiObservationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DiscoveredApiObservation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudApiHubV1.ListDiscoveredApiObservationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listDiscoveredApiObservations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDiscoveredApiObservationsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<DiscoveredApiObservation, Swift.Error> & Sendable {
    let request = ListDiscoveredApiObservationsRequest().with {
      $0.parent = parent
    }
    return self.listDiscoveredApiObservationsByItems(request: request)
  }

  public func getDiscoveredApiObservation(request: GetDiscoveredApiObservationRequest) async throws
    -> GoogleCloudApiHubV1.DiscoveredApiObservation
  {
    try await self.getDiscoveredApiObservation(request: request, options: .init())
  }

  public func getDiscoveredApiObservation(
    request: GetDiscoveredApiObservationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.DiscoveredApiObservation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDiscoveredApiObservation(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.DiscoveredApiObservation {
    let request = GetDiscoveredApiObservationRequest().with {
      $0.name = name
    }
    return try await self.getDiscoveredApiObservation(request: request)
  }

  public func listDiscoveredApiOperations(request: ListDiscoveredApiOperationsRequest) async throws
    -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse
  {
    try await self.listDiscoveredApiOperations(request: request, options: .init())
  }

  public func listDiscoveredApiOperations(
    request: ListDiscoveredApiOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDiscoveredApiOperationsByItems(
    request: ListDiscoveredApiOperationsRequest
  ) -> any AsyncSequence<DiscoveredApiOperation, Swift.Error> & Sendable {
    self.listDiscoveredApiOperationsByItems(request: request, options: .init())
  }

  /// Lists all the DiscoveredAPIOperations in a given project, location and
  /// ApiObservation.
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListDiscoveredApiOperations")
  public func listDiscoveredApiOperationsByItems(
    request: ListDiscoveredApiOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<DiscoveredApiOperation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudApiHubV1.ListDiscoveredApiOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listDiscoveredApiOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDiscoveredApiOperationsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<DiscoveredApiOperation, Swift.Error> & Sendable {
    let request = ListDiscoveredApiOperationsRequest().with {
      $0.parent = parent
    }
    return self.listDiscoveredApiOperationsByItems(request: request)
  }

  public func getDiscoveredApiOperation(request: GetDiscoveredApiOperationRequest) async throws
    -> GoogleCloudApiHubV1.DiscoveredApiOperation
  {
    try await self.getDiscoveredApiOperation(request: request, options: .init())
  }

  public func getDiscoveredApiOperation(
    request: GetDiscoveredApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.DiscoveredApiOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDiscoveredApiOperation(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.DiscoveredApiOperation {
    let request = GetDiscoveredApiOperationRequest().with {
      $0.name = name
    }
    return try await self.getDiscoveredApiOperation(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDiscovery_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
