// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ApiHubResource is one of the resources such as Api, Operation, Deployment,
/// Definition, Spec and Version resources stored in API-Hub.
public struct ApiHubResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var resource: ResourceOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApiHubResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApiHubResource().with { $0.api = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let api = CodingKeys(stringValue: "api")
    static let operation = CodingKeys(stringValue: "operation")
    static let deployment = CodingKeys(stringValue: "deployment")
    static let spec = CodingKeys(stringValue: "spec")
    static let definition = CodingKeys(stringValue: "definition")
    static let version = CodingKeys(stringValue: "version")

    static let _knownKeys: Set<Swift.String> = [
      "api",
      "operation",
      "deployment",
      "spec",
      "definition",
      "version",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var resource: ResourceOneOf? = nil
    let resourceCheckAndSet = {
      if resource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resource'"))
      }
      resource = $0
    }
    if let api = try container.decodeIfPresent(Api?.self, forKey: .api) {
      try resourceCheckAndSet(.api(api))
    }
    if let operation = try container.decodeIfPresent(ApiOperation?.self, forKey: .operation) {
      try resourceCheckAndSet(.operation(operation))
    }
    if let deployment = try container.decodeIfPresent(Deployment?.self, forKey: .deployment) {
      try resourceCheckAndSet(.deployment(deployment))
    }
    if let spec = try container.decodeIfPresent(Spec?.self, forKey: .spec) {
      try resourceCheckAndSet(.spec(spec))
    }
    if let definition = try container.decodeIfPresent(Definition?.self, forKey: .definition) {
      try resourceCheckAndSet(.definition(definition))
    }
    if let version = try container.decodeIfPresent(Version?.self, forKey: .version) {
      try resourceCheckAndSet(.version(version))
    }
    self.resource = resource
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.resource {
      switch choice {
      case .api(let value):
        try container.encode(value, forKey: .api)
      case .operation(let value):
        try container.encode(value, forKey: .operation)
      case .deployment(let value):
        try container.encode(value, forKey: .deployment)
      case .spec(let value):
        try container.encode(value, forKey: .spec)
      case .definition(let value):
        try container.encode(value, forKey: .definition)
      case .version(let value):
        try container.encode(value, forKey: .version)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum ResourceOneOf: Codable, Equatable, Sendable {
    /// This represents Api resource in search results. Only name, display_name,
    /// description and owner fields are populated in search results.
    indirect case api(Api?)
    /// This represents ApiOperation resource in search results. Only name,
    /// description, spec and details fields are populated in search results.
    indirect case operation(ApiOperation?)
    /// This represents Deployment resource in search results. Only name,
    /// display_name, description, deployment_type and api_versions fields are
    /// populated in search results.
    indirect case deployment(Deployment?)
    /// This represents Spec resource in search results. Only name,
    /// display_name, description, spec_type and documentation fields are
    /// populated in search results.
    indirect case spec(Spec?)
    /// This represents Definition resource in search results.
    /// Only name field is populated in search results.
    indirect case definition(Definition?)
    /// This represents Version resource in search results. Only name,
    /// display_name, description, lifecycle, compliance and accreditation fields
    /// are populated in search results.
    indirect case version(Version?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.ApiHubResource"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
