// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// This service provides methods for various operations related to a
/// [Dependency][google.cloud.apihub.v1.Dependency] in the API hub.
///
/// [google.cloud.apihub.v1.Dependency]: <doc:Dependency>
///
/// @Snippet(path: "ApiHubDependenciesQuickstart")
public final class ApiHubDependenciesClient: Clients.ApiHubDependenciesProtocol, Sendable {
  let inner: any Clients.ApiHubDependenciesStub

  /// Creates a new `ApiHubDependenciesClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiHubDependenciesStub = try Clients.ApiHubDependenciesTransport(options)
    inner = Clients.ApiHubDependenciesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiHubDependenciesLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create a dependency between two entities in the API hub.
  ///
  /// @Snippet(path: "ApiHubDependencies_CreateDependency")
  public func createDependency(
    request: CreateDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    try await self.inner.createDependency(request: request, options: options)
  }

  /// Get details about a dependency resource in the API hub.
  ///
  /// @Snippet(path: "ApiHubDependencies_GetDependency")
  public func getDependency(
    request: GetDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    try await self.inner.getDependency(request: request, options: options)
  }

  /// Update a dependency based on the
  /// [update_mask][google.cloud.apihub.v1.UpdateDependencyRequest.update_mask]
  /// provided in the request.
  ///
  /// The following fields in the [dependency][google.cloud.apihub.v1.Dependency]
  /// can be updated:
  /// * [description][google.cloud.apihub.v1.Dependency.description]
  ///
  /// [google.cloud.apihub.v1.Dependency]: <doc:Dependency>
  /// [google.cloud.apihub.v1.Dependency.description]: <doc:Dependency/description>
  /// [google.cloud.apihub.v1.UpdateDependencyRequest.update_mask]: <doc:UpdateDependencyRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHubDependencies_UpdateDependency")
  public func updateDependency(
    request: UpdateDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    try await self.inner.updateDependency(request: request, options: options)
  }

  /// Delete the dependency resource.
  ///
  /// @Snippet(path: "ApiHubDependencies_DeleteDependency")
  public func deleteDependency(
    request: DeleteDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDependency(request: request, options: options)
  }

  /// List dependencies based on the provided filter and pagination parameters.
  ///
  /// @Snippet(path: "ApiHubDependencies_ListDependencies")
  public func listDependencies(
    request: ListDependenciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDependenciesResponse {
    try await self.inner.listDependencies(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHubDependencies_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ApiHubDependencies_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDependencies_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDependencies_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDependencies_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDependencies_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiHubDependenciesClient`.
  ///
  /// To mock `ApiHubDependenciesClient` change your functions to receive
  /// `some ApiHubDependenciesProtocol` or `any ApiHubDependenciesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiHubDependenciesProtocol: Sendable {
    /// See `ApiHubDependenciesClient.createDependency`.
    func createDependency(
      request: CreateDependencyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Dependency

    /// See `ApiHubDependenciesClient.getDependency`.
    func getDependency(
      request: GetDependencyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Dependency

    /// See `ApiHubDependenciesClient.updateDependency`.
    func updateDependency(
      request: UpdateDependencyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Dependency

    /// See `ApiHubDependenciesClient.deleteDependency`.
    func deleteDependency(
      request: DeleteDependencyRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubDependenciesClient.listDependencies`.
    func listDependencies(
      request: ListDependenciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDependenciesResponse

    /// See `ApiHubDependenciesClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ApiHubDependenciesClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ApiHubDependenciesClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ApiHubDependenciesClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubDependenciesClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ApiHubDependenciesProtocol {
  public func createDependency(request: CreateDependencyRequest) async throws
    -> GoogleCloudApiHubV1.Dependency
  {
    try await self.createDependency(request: request, options: .init())
  }

  public func createDependency(
    request: CreateDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDependency(
    parent: Swift.String,
    dependency: Dependency?,
    dependencyId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    let request = CreateDependencyRequest().with {
      $0.parent = parent
      $0.dependency = dependency
      $0.dependencyId = dependencyId
    }
    return try await self.createDependency(request: request)
  }

  public func getDependency(request: GetDependencyRequest) async throws
    -> GoogleCloudApiHubV1.Dependency
  {
    try await self.getDependency(request: request, options: .init())
  }

  public func getDependency(
    request: GetDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDependency(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    let request = GetDependencyRequest().with {
      $0.name = name
    }
    return try await self.getDependency(request: request)
  }

  public func updateDependency(request: UpdateDependencyRequest) async throws
    -> GoogleCloudApiHubV1.Dependency
  {
    try await self.updateDependency(request: request, options: .init())
  }

  public func updateDependency(
    request: UpdateDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateDependency(
    dependency: Dependency?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Dependency {
    let request = UpdateDependencyRequest().with {
      $0.dependency = dependency
      $0.updateMask = updateMask
    }
    return try await self.updateDependency(request: request)
  }

  public func deleteDependency(request: DeleteDependencyRequest) async throws {
    try await self.deleteDependency(request: request, options: .init())
  }

  public func deleteDependency(
    request: DeleteDependencyRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDependency(
    name: Swift.String,
  ) async throws {
    let request = DeleteDependencyRequest().with {
      $0.name = name
    }
    try await self.deleteDependency(request: request)
  }

  public func listDependencies(request: ListDependenciesRequest) async throws
    -> GoogleCloudApiHubV1.ListDependenciesResponse
  {
    try await self.listDependencies(request: request, options: .init())
  }

  public func listDependencies(
    request: ListDependenciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDependenciesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDependenciesByItems(
    request: ListDependenciesRequest
  ) -> any AsyncSequence<Dependency, Swift.Error> {
    self.listDependenciesByItems(request: request, options: .init())
  }

  /// List dependencies based on the provided filter and pagination parameters.
  ///
  /// @Snippet(path: "ApiHubDependencies_ListDependencies")
  public func listDependenciesByItems(
    request: ListDependenciesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Dependency, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListDependenciesResponse in
      var request = request
      request.pageToken = token
      return try await self.listDependencies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDependenciesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Dependency, Swift.Error> {
    let request = ListDependenciesRequest().with {
      $0.parent = parent
    }
    return self.listDependenciesByItems(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHubDependencies_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHubDependencies_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
