// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// This service provides all methods related to the API hub.
///
/// @Snippet(path: "ApiHubQuickstart")
public final class ApiHubClient: Clients.ApiHubProtocol, Sendable {
  let inner: any Clients.ApiHubStub

  /// Creates a new `ApiHubClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiHubStub = try Clients.ApiHubTransport(options)
    inner = Clients.ApiHubRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiHubLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Create an API resource in the API hub.
  /// Once an API resource is created, versions can be added to it.
  ///
  /// @Snippet(path: "ApiHub_CreateApi")
  public func createApi(
    request: CreateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Api {
    try await self.inner.createApi(request: request, options: options)
  }

  /// Get API resource details including the API versions contained in it.
  ///
  /// @Snippet(path: "ApiHub_GetApi")
  public func getApi(
    request: GetApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Api {
    try await self.inner.getApi(request: request, options: options)
  }

  /// List API resources in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListApis")
  public func listApis(
    request: ListApisRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListApisResponse {
    try await self.inner.listApis(request: request, options: options)
  }

  /// Update an API resource in the API hub. The following fields in the
  /// [API][google.cloud.apihub.v1.Api] can be updated:
  ///
  /// * [display_name][google.cloud.apihub.v1.Api.display_name]
  /// * [description][google.cloud.apihub.v1.Api.description]
  /// * [owner][google.cloud.apihub.v1.Api.owner]
  /// * [documentation][google.cloud.apihub.v1.Api.documentation]
  /// * [target_user][google.cloud.apihub.v1.Api.target_user]
  /// * [team][google.cloud.apihub.v1.Api.team]
  /// * [business_unit][google.cloud.apihub.v1.Api.business_unit]
  /// * [maturity_level][google.cloud.apihub.v1.Api.maturity_level]
  /// * [api_style][google.cloud.apihub.v1.Api.api_style]
  /// * [attributes][google.cloud.apihub.v1.Api.attributes]
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateApiRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// Updating the owner field requires complete owner message
  /// and updates both owner and email fields.
  ///
  /// [google.cloud.apihub.v1.Api]: <doc:Api>
  /// [google.cloud.apihub.v1.Api.api_style]: <doc:Api/apiStyle>
  /// [google.cloud.apihub.v1.Api.attributes]: <doc:Api/attributes>
  /// [google.cloud.apihub.v1.Api.business_unit]: <doc:Api/businessUnit>
  /// [google.cloud.apihub.v1.Api.description]: <doc:Api/description>
  /// [google.cloud.apihub.v1.Api.display_name]: <doc:Api/displayName>
  /// [google.cloud.apihub.v1.Api.documentation]: <doc:Api/documentation>
  /// [google.cloud.apihub.v1.Api.maturity_level]: <doc:Api/maturityLevel>
  /// [google.cloud.apihub.v1.Api.owner]: <doc:Api/owner>
  /// [google.cloud.apihub.v1.Api.target_user]: <doc:Api/targetUser>
  /// [google.cloud.apihub.v1.Api.team]: <doc:Api/team>
  /// [google.cloud.apihub.v1.UpdateApiRequest.update_mask]: <doc:UpdateApiRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHub_UpdateApi")
  public func updateApi(
    request: UpdateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Api {
    try await self.inner.updateApi(request: request, options: options)
  }

  /// Delete an API resource in the API hub. API can only be deleted if all
  /// underlying versions are deleted.
  ///
  /// @Snippet(path: "ApiHub_DeleteApi")
  public func deleteApi(
    request: DeleteApiRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteApi(request: request, options: options)
  }

  /// Create an API version for an API resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_CreateVersion")
  public func createVersion(
    request: CreateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Version {
    try await self.inner.createVersion(request: request, options: options)
  }

  /// Get details about the API version of an API resource. This will include
  /// information about the specs and operations present in the API
  /// version as well as the deployments linked to it.
  ///
  /// @Snippet(path: "ApiHub_GetVersion")
  public func getVersion(
    request: GetVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Version {
    try await self.inner.getVersion(request: request, options: options)
  }

  /// List API versions of an API resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListVersions")
  public func listVersions(
    request: ListVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListVersionsResponse {
    try await self.inner.listVersions(request: request, options: options)
  }

  /// Update API version. The following fields in the
  /// [version][google.cloud.apihub.v1.Version] can be updated currently:
  ///
  /// * [display_name][google.cloud.apihub.v1.Version.display_name]
  /// * [description][google.cloud.apihub.v1.Version.description]
  /// * [documentation][google.cloud.apihub.v1.Version.documentation]
  /// * [deployments][google.cloud.apihub.v1.Version.deployments]
  /// * [lifecycle][google.cloud.apihub.v1.Version.lifecycle]
  /// * [compliance][google.cloud.apihub.v1.Version.compliance]
  /// * [accreditation][google.cloud.apihub.v1.Version.accreditation]
  /// * [attributes][google.cloud.apihub.v1.Version.attributes]
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateVersionRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// [google.cloud.apihub.v1.UpdateVersionRequest.update_mask]: <doc:UpdateVersionRequest/updateMask>
  /// [google.cloud.apihub.v1.Version]: <doc:Version>
  /// [google.cloud.apihub.v1.Version.accreditation]: <doc:Version/accreditation>
  /// [google.cloud.apihub.v1.Version.attributes]: <doc:Version/attributes>
  /// [google.cloud.apihub.v1.Version.compliance]: <doc:Version/compliance>
  /// [google.cloud.apihub.v1.Version.deployments]: <doc:Version/deployments>
  /// [google.cloud.apihub.v1.Version.description]: <doc:Version/description>
  /// [google.cloud.apihub.v1.Version.display_name]: <doc:Version/displayName>
  /// [google.cloud.apihub.v1.Version.documentation]: <doc:Version/documentation>
  /// [google.cloud.apihub.v1.Version.lifecycle]: <doc:Version/lifecycle>
  ///
  /// @Snippet(path: "ApiHub_UpdateVersion")
  public func updateVersion(
    request: UpdateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Version {
    try await self.inner.updateVersion(request: request, options: options)
  }

  /// Delete an API version. Version can only be deleted if all underlying specs,
  /// operations, definitions and linked deployments are deleted.
  ///
  /// @Snippet(path: "ApiHub_DeleteVersion")
  public func deleteVersion(
    request: DeleteVersionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteVersion(request: request, options: options)
  }

  /// Add a spec to an API version in the API hub.
  /// Multiple specs can be added to an API version.
  /// Note, while adding a spec, at least one of `contents` or `source_uri` must
  /// be provided. If `contents` is provided, then `spec_type` must also be
  /// provided.
  ///
  /// On adding a spec with contents to the version, the operations present in it
  /// will be added to the version.Note that the file contents in the spec should
  /// be of the same type as defined in the
  /// `projects/{project}/locations/{location}/attributes/system-spec-type`
  /// attribute associated with spec resource. Note that specs of various types
  /// can be uploaded, however parsing of details is supported for OpenAPI spec
  /// currently.
  ///
  /// In order to access the information parsed from the spec, use the
  /// [GetSpec][google.cloud.apihub.v1.ApiHub.GetSpec] method.
  /// In order to access the raw contents for a particular spec, use the
  /// [GetSpecContents][google.cloud.apihub.v1.ApiHub.GetSpecContents] method.
  /// In order to access the operations parsed from the spec, use the
  /// [ListAPIOperations][google.cloud.apihub.v1.ApiHub.ListApiOperations]
  /// method.
  ///
  /// [google.cloud.apihub.v1.ApiHub.GetSpec]: <doc:ApiHubClient/getSpec(request:options:)>
  /// [google.cloud.apihub.v1.ApiHub.GetSpecContents]: <doc:ApiHubClient/getSpecContents(request:options:)>
  /// [google.cloud.apihub.v1.ApiHub.ListApiOperations]: <doc:ApiHubClient/listApiOperations(request:options:)>
  ///
  /// @Snippet(path: "ApiHub_CreateSpec")
  public func createSpec(
    request: CreateSpecRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Spec {
    try await self.inner.createSpec(request: request, options: options)
  }

  /// Get details about the information parsed from a spec.
  /// Note that this method does not return the raw spec contents.
  /// Use [GetSpecContents][google.cloud.apihub.v1.ApiHub.GetSpecContents] method
  /// to retrieve the same.
  ///
  /// [google.cloud.apihub.v1.ApiHub.GetSpecContents]: <doc:ApiHubClient/getSpecContents(request:options:)>
  ///
  /// @Snippet(path: "ApiHub_GetSpec")
  public func getSpec(
    request: GetSpecRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Spec {
    try await self.inner.getSpec(request: request, options: options)
  }

  /// Get spec contents.
  ///
  /// @Snippet(path: "ApiHub_GetSpecContents")
  public func getSpecContents(
    request: GetSpecContentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.SpecContents {
    try await self.inner.getSpecContents(request: request, options: options)
  }

  /// List specs corresponding to a particular API resource.
  ///
  /// @Snippet(path: "ApiHub_ListSpecs")
  public func listSpecs(
    request: ListSpecsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListSpecsResponse {
    try await self.inner.listSpecs(request: request, options: options)
  }

  /// Update spec. The following fields in the
  /// [spec][google.cloud.apihub.v1.Spec] can be updated:
  ///
  /// * [display_name][google.cloud.apihub.v1.Spec.display_name]
  /// * [source_uri][google.cloud.apihub.v1.Spec.source_uri]
  /// * [lint_response][google.cloud.apihub.v1.Spec.lint_response]
  /// * [attributes][google.cloud.apihub.v1.Spec.attributes]
  /// * [contents][google.cloud.apihub.v1.Spec.contents]
  /// * [spec_type][google.cloud.apihub.v1.Spec.spec_type]
  ///
  /// In case of an OAS spec, updating spec contents can lead to:
  /// 1. Creation, deletion and update of operations.
  /// 2. Creation, deletion and update of definitions.
  /// 3. Update of other info parsed out from the new spec.
  ///
  /// In case of contents or source_uri being present in update mask, spec_type
  /// must also be present. Also, spec_type can not be present in update mask if
  /// contents or source_uri is not present.
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateSpecRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// [google.cloud.apihub.v1.Spec]: <doc:Spec>
  /// [google.cloud.apihub.v1.Spec.attributes]: <doc:Spec/attributes>
  /// [google.cloud.apihub.v1.Spec.contents]: <doc:Spec/contents>
  /// [google.cloud.apihub.v1.Spec.display_name]: <doc:Spec/displayName>
  /// [google.cloud.apihub.v1.Spec.lint_response]: <doc:Spec/lintResponse>
  /// [google.cloud.apihub.v1.Spec.source_uri]: <doc:Spec/sourceUri>
  /// [google.cloud.apihub.v1.Spec.spec_type]: <doc:Spec/specType>
  /// [google.cloud.apihub.v1.UpdateSpecRequest.update_mask]: <doc:UpdateSpecRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHub_UpdateSpec")
  public func updateSpec(
    request: UpdateSpecRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Spec {
    try await self.inner.updateSpec(request: request, options: options)
  }

  /// Delete a spec.
  /// Deleting a spec will also delete the associated operations from the
  /// version.
  ///
  /// @Snippet(path: "ApiHub_DeleteSpec")
  public func deleteSpec(
    request: DeleteSpecRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSpec(request: request, options: options)
  }

  /// Create an apiOperation in an API version.
  /// An apiOperation can be created only if the version has no apiOperations
  /// which were created by parsing a spec.
  ///
  /// @Snippet(path: "ApiHub_CreateApiOperation")
  public func createApiOperation(
    request: CreateApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    try await self.inner.createApiOperation(request: request, options: options)
  }

  /// Get details about a particular operation in API version.
  ///
  /// @Snippet(path: "ApiHub_GetApiOperation")
  public func getApiOperation(
    request: GetApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    try await self.inner.getApiOperation(request: request, options: options)
  }

  /// List operations in an API version.
  ///
  /// @Snippet(path: "ApiHub_ListApiOperations")
  public func listApiOperations(
    request: ListApiOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListApiOperationsResponse {
    try await self.inner.listApiOperations(request: request, options: options)
  }

  /// Update an operation in an API version. The following fields in the
  /// [ApiOperation resource][google.cloud.apihub.v1.ApiOperation] can be
  /// updated:
  ///
  /// * [details.description][ApiOperation.details.description]
  /// * [details.documentation][ApiOperation.details.documentation]
  /// * [details.http_operation.path][ApiOperation.details.http_operation.path.path]
  /// * [details.http_operation.method][ApiOperation.details.http_operation.method]
  /// * [details.deprecated][ApiOperation.details.deprecated]
  /// * [attributes][google.cloud.apihub.v1.ApiOperation.attributes]
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateApiOperationRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// An operation can be updated only if the operation was created via
  /// [CreateApiOperation][google.cloud.apihub.v1.ApiHub.CreateApiOperation] API.
  /// If the operation was created by parsing the spec, then it can be edited by
  /// updating the spec.
  ///
  /// [google.cloud.apihub.v1.ApiHub.CreateApiOperation]: <doc:ApiHubClient/createApiOperation(request:options:)>
  /// [google.cloud.apihub.v1.ApiOperation]: <doc:ApiOperation>
  /// [google.cloud.apihub.v1.ApiOperation.attributes]: <doc:ApiOperation/attributes>
  /// [google.cloud.apihub.v1.UpdateApiOperationRequest.update_mask]: <doc:UpdateApiOperationRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHub_UpdateApiOperation")
  public func updateApiOperation(
    request: UpdateApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    try await self.inner.updateApiOperation(request: request, options: options)
  }

  /// Delete an operation in an API version and we can delete only the
  /// operations created via create API. If the operation was created by parsing
  /// the spec, then it can be deleted by editing or deleting the spec.
  ///
  /// @Snippet(path: "ApiHub_DeleteApiOperation")
  public func deleteApiOperation(
    request: DeleteApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteApiOperation(request: request, options: options)
  }

  /// Get details about a definition in an API version.
  ///
  /// @Snippet(path: "ApiHub_GetDefinition")
  public func getDefinition(
    request: GetDefinitionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Definition {
    try await self.inner.getDefinition(request: request, options: options)
  }

  /// Create a deployment resource in the API hub.
  /// Once a deployment resource is created, it can be associated with API
  /// versions.
  ///
  /// @Snippet(path: "ApiHub_CreateDeployment")
  public func createDeployment(
    request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    try await self.inner.createDeployment(request: request, options: options)
  }

  /// Get details about a deployment and the API versions linked to it.
  ///
  /// @Snippet(path: "ApiHub_GetDeployment")
  public func getDeployment(
    request: GetDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    try await self.inner.getDeployment(request: request, options: options)
  }

  /// List deployment resources in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListDeployments")
  public func listDeployments(
    request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDeploymentsResponse {
    try await self.inner.listDeployments(request: request, options: options)
  }

  /// Update a deployment resource in the API hub. The following fields in the
  /// [deployment resource][google.cloud.apihub.v1.Deployment] can be
  /// updated:
  ///
  /// * [display_name][google.cloud.apihub.v1.Deployment.display_name]
  /// * [description][google.cloud.apihub.v1.Deployment.description]
  /// * [documentation][google.cloud.apihub.v1.Deployment.documentation]
  /// * [deployment_type][google.cloud.apihub.v1.Deployment.deployment_type]
  /// * [resource_uri][google.cloud.apihub.v1.Deployment.resource_uri]
  /// * [endpoints][google.cloud.apihub.v1.Deployment.endpoints]
  /// * [slo][google.cloud.apihub.v1.Deployment.slo]
  /// * [environment][google.cloud.apihub.v1.Deployment.environment]
  /// * [attributes][google.cloud.apihub.v1.Deployment.attributes]
  /// * [source_project] [google.cloud.apihub.v1.Deployment.source_project]
  /// * [source_environment]
  /// [google.cloud.apihub.v1.Deployment.source_environment]
  /// * [management_url][google.cloud.apihub.v1.Deployment.management_url]
  /// * [source_uri][google.cloud.apihub.v1.Deployment.source_uri]
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateDeploymentRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// [google.cloud.apihub.v1.Deployment]: <doc:Deployment>
  /// [google.cloud.apihub.v1.Deployment.attributes]: <doc:Deployment/attributes>
  /// [google.cloud.apihub.v1.Deployment.deployment_type]: <doc:Deployment/deploymentType>
  /// [google.cloud.apihub.v1.Deployment.description]: <doc:Deployment/description>
  /// [google.cloud.apihub.v1.Deployment.display_name]: <doc:Deployment/displayName>
  /// [google.cloud.apihub.v1.Deployment.documentation]: <doc:Deployment/documentation>
  /// [google.cloud.apihub.v1.Deployment.endpoints]: <doc:Deployment/endpoints>
  /// [google.cloud.apihub.v1.Deployment.environment]: <doc:Deployment/environment>
  /// [google.cloud.apihub.v1.Deployment.management_url]: <doc:Deployment/managementUrl>
  /// [google.cloud.apihub.v1.Deployment.resource_uri]: <doc:Deployment/resourceUri>
  /// [google.cloud.apihub.v1.Deployment.slo]: <doc:Deployment/slo>
  /// [google.cloud.apihub.v1.Deployment.source_uri]: <doc:Deployment/sourceUri>
  /// [google.cloud.apihub.v1.UpdateDeploymentRequest.update_mask]: <doc:UpdateDeploymentRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHub_UpdateDeployment")
  public func updateDeployment(
    request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    try await self.inner.updateDeployment(request: request, options: options)
  }

  /// Delete a deployment resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_DeleteDeployment")
  public func deleteDeployment(
    request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteDeployment(request: request, options: options)
  }

  /// Create a user defined attribute.
  ///
  /// Certain pre defined attributes are already created by the API hub. These
  /// attributes will have type as `SYSTEM_DEFINED` and can be listed via
  /// [ListAttributes][google.cloud.apihub.v1.ApiHub.ListAttributes] method.
  /// Allowed values for the same can be updated via
  /// [UpdateAttribute][google.cloud.apihub.v1.ApiHub.UpdateAttribute] method.
  ///
  /// [google.cloud.apihub.v1.ApiHub.ListAttributes]: <doc:ApiHubClient/listAttributes(request:options:)>
  /// [google.cloud.apihub.v1.ApiHub.UpdateAttribute]: <doc:ApiHubClient/updateAttribute(request:options:)>
  ///
  /// @Snippet(path: "ApiHub_CreateAttribute")
  public func createAttribute(
    request: CreateAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    try await self.inner.createAttribute(request: request, options: options)
  }

  /// Get details about the attribute.
  ///
  /// @Snippet(path: "ApiHub_GetAttribute")
  public func getAttribute(
    request: GetAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    try await self.inner.getAttribute(request: request, options: options)
  }

  /// Update the attribute.  The following fields in the
  /// [Attribute resource][google.cloud.apihub.v1.Attribute] can be updated:
  ///
  /// * [display_name][google.cloud.apihub.v1.Attribute.display_name]
  /// The display name can be updated for user defined attributes only.
  /// * [description][google.cloud.apihub.v1.Attribute.description]
  /// The description can be updated for user defined attributes only.
  /// * [allowed_values][google.cloud.apihub.v1.Attribute.allowed_values]
  /// To update the list of allowed values, clients need to use the fetched list
  /// of allowed values and add or remove values to or from the same list.
  /// The mutable allowed values can be updated for both user defined and System
  /// defined attributes. The immutable allowed values cannot be updated or
  /// deleted. The updated list of allowed values cannot be empty. If an allowed
  /// value that is already used by some resource's attribute is deleted, then
  /// the association between the resource and the attribute value will also be
  /// deleted.
  /// * [cardinality][google.cloud.apihub.v1.Attribute.cardinality]
  /// The cardinality can be updated for user defined attributes only.
  /// Cardinality can only be increased during an update.
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateAttributeRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// [google.cloud.apihub.v1.Attribute]: <doc:Attribute>
  /// [google.cloud.apihub.v1.Attribute.allowed_values]: <doc:Attribute/allowedValues>
  /// [google.cloud.apihub.v1.Attribute.cardinality]: <doc:Attribute/cardinality>
  /// [google.cloud.apihub.v1.Attribute.description]: <doc:Attribute/description>
  /// [google.cloud.apihub.v1.Attribute.display_name]: <doc:Attribute/displayName>
  /// [google.cloud.apihub.v1.UpdateAttributeRequest.update_mask]: <doc:UpdateAttributeRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHub_UpdateAttribute")
  public func updateAttribute(
    request: UpdateAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    try await self.inner.updateAttribute(request: request, options: options)
  }

  /// Delete an attribute.
  ///
  /// Note: System defined attributes cannot be deleted. All
  /// associations of the attribute being deleted with any API hub resource will
  /// also get deleted.
  ///
  /// @Snippet(path: "ApiHub_DeleteAttribute")
  public func deleteAttribute(
    request: DeleteAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAttribute(request: request, options: options)
  }

  /// List all attributes.
  ///
  /// @Snippet(path: "ApiHub_ListAttributes")
  public func listAttributes(
    request: ListAttributesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListAttributesResponse {
    try await self.inner.listAttributes(request: request, options: options)
  }

  /// Search across API-Hub resources.
  ///
  /// @Snippet(path: "ApiHub_SearchResources")
  public func searchResources(
    request: SearchResourcesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.SearchResourcesResponse {
    try await self.inner.searchResources(request: request, options: options)
  }

  /// Create an External API resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_CreateExternalApi")
  public func createExternalApi(
    request: CreateExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    try await self.inner.createExternalApi(request: request, options: options)
  }

  /// Get details about an External API resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_GetExternalApi")
  public func getExternalApi(
    request: GetExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    try await self.inner.getExternalApi(request: request, options: options)
  }

  /// Update an External API resource in the API hub. The following fields can be
  /// updated:
  ///
  /// * [display_name][google.cloud.apihub.v1.ExternalApi.display_name]
  /// * [description][google.cloud.apihub.v1.ExternalApi.description]
  /// * [documentation][google.cloud.apihub.v1.ExternalApi.documentation]
  /// * [endpoints][google.cloud.apihub.v1.ExternalApi.endpoints]
  /// * [paths][google.cloud.apihub.v1.ExternalApi.paths]
  ///
  /// The
  /// [update_mask][google.cloud.apihub.v1.UpdateExternalApiRequest.update_mask]
  /// should be used to specify the fields being updated.
  ///
  /// [google.cloud.apihub.v1.ExternalApi.description]: <doc:ExternalApi/description>
  /// [google.cloud.apihub.v1.ExternalApi.display_name]: <doc:ExternalApi/displayName>
  /// [google.cloud.apihub.v1.ExternalApi.documentation]: <doc:ExternalApi/documentation>
  /// [google.cloud.apihub.v1.ExternalApi.endpoints]: <doc:ExternalApi/endpoints>
  /// [google.cloud.apihub.v1.ExternalApi.paths]: <doc:ExternalApi/paths>
  /// [google.cloud.apihub.v1.UpdateExternalApiRequest.update_mask]: <doc:UpdateExternalApiRequest/updateMask>
  ///
  /// @Snippet(path: "ApiHub_UpdateExternalApi")
  public func updateExternalApi(
    request: UpdateExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    try await self.inner.updateExternalApi(request: request, options: options)
  }

  /// Delete an External API resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_DeleteExternalApi")
  public func deleteExternalApi(
    request: DeleteExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteExternalApi(request: request, options: options)
  }

  /// List External API resources in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListExternalApis")
  public func listExternalApis(
    request: ListExternalApisRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListExternalApisResponse {
    try await self.inner.listExternalApis(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHub_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ApiHub_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHub_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHub_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHub_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHub_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiHubClient`.
  ///
  /// To mock `ApiHubClient` change your functions to receive
  /// `some ApiHubProtocol` or `any ApiHubProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiHubProtocol: Sendable {
    /// See `ApiHubClient.createApi`.
    func createApi(
      request: CreateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Api

    /// See `ApiHubClient.getApi`.
    func getApi(
      request: GetApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Api

    /// See `ApiHubClient.listApis`.
    func listApis(
      request: ListApisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListApisResponse

    /// See `ApiHubClient.updateApi`.
    func updateApi(
      request: UpdateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Api

    /// See `ApiHubClient.deleteApi`.
    func deleteApi(
      request: DeleteApiRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.createVersion`.
    func createVersion(
      request: CreateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Version

    /// See `ApiHubClient.getVersion`.
    func getVersion(
      request: GetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Version

    /// See `ApiHubClient.listVersions`.
    func listVersions(
      request: ListVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListVersionsResponse

    /// See `ApiHubClient.updateVersion`.
    func updateVersion(
      request: UpdateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Version

    /// See `ApiHubClient.deleteVersion`.
    func deleteVersion(
      request: DeleteVersionRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.createSpec`.
    func createSpec(
      request: CreateSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Spec

    /// See `ApiHubClient.getSpec`.
    func getSpec(
      request: GetSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Spec

    /// See `ApiHubClient.getSpecContents`.
    func getSpecContents(
      request: GetSpecContentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.SpecContents

    /// See `ApiHubClient.listSpecs`.
    func listSpecs(
      request: ListSpecsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListSpecsResponse

    /// See `ApiHubClient.updateSpec`.
    func updateSpec(
      request: UpdateSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Spec

    /// See `ApiHubClient.deleteSpec`.
    func deleteSpec(
      request: DeleteSpecRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.createApiOperation`.
    func createApiOperation(
      request: CreateApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ApiOperation

    /// See `ApiHubClient.getApiOperation`.
    func getApiOperation(
      request: GetApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ApiOperation

    /// See `ApiHubClient.listApiOperations`.
    func listApiOperations(
      request: ListApiOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListApiOperationsResponse

    /// See `ApiHubClient.updateApiOperation`.
    func updateApiOperation(
      request: UpdateApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ApiOperation

    /// See `ApiHubClient.deleteApiOperation`.
    func deleteApiOperation(
      request: DeleteApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.getDefinition`.
    func getDefinition(
      request: GetDefinitionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Definition

    /// See `ApiHubClient.createDeployment`.
    func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Deployment

    /// See `ApiHubClient.getDeployment`.
    func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Deployment

    /// See `ApiHubClient.listDeployments`.
    func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDeploymentsResponse

    /// See `ApiHubClient.updateDeployment`.
    func updateDeployment(
      request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Deployment

    /// See `ApiHubClient.deleteDeployment`.
    func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.createAttribute`.
    func createAttribute(
      request: CreateAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Attribute

    /// See `ApiHubClient.getAttribute`.
    func getAttribute(
      request: GetAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Attribute

    /// See `ApiHubClient.updateAttribute`.
    func updateAttribute(
      request: UpdateAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Attribute

    /// See `ApiHubClient.deleteAttribute`.
    func deleteAttribute(
      request: DeleteAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.listAttributes`.
    func listAttributes(
      request: ListAttributesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListAttributesResponse

    /// See `ApiHubClient.searchResources`.
    func searchResources(
      request: SearchResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.SearchResourcesResponse

    /// See `ApiHubClient.createExternalApi`.
    func createExternalApi(
      request: CreateExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ExternalApi

    /// See `ApiHubClient.getExternalApi`.
    func getExternalApi(
      request: GetExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ExternalApi

    /// See `ApiHubClient.updateExternalApi`.
    func updateExternalApi(
      request: UpdateExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ExternalApi

    /// See `ApiHubClient.deleteExternalApi`.
    func deleteExternalApi(
      request: DeleteExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.listExternalApis`.
    func listExternalApis(
      request: ListExternalApisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListExternalApisResponse

    /// See `ApiHubClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ApiHubClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ApiHubClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ApiHubClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiHubClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ApiHubProtocol {
  public func createApi(request: CreateApiRequest) async throws -> GoogleCloudApiHubV1.Api {
    try await self.createApi(request: request, options: .init())
  }

  public func createApi(
    request: CreateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Api {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApi(
    parent: Swift.String,
    api: Api?,
    apiId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Api {
    let request = CreateApiRequest().with {
      $0.parent = parent
      $0.api = api
      $0.apiId = apiId
    }
    return try await self.createApi(request: request)
  }

  public func getApi(request: GetApiRequest) async throws -> GoogleCloudApiHubV1.Api {
    try await self.getApi(request: request, options: .init())
  }

  public func getApi(
    request: GetApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Api {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getApi(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Api {
    let request = GetApiRequest().with {
      $0.name = name
    }
    return try await self.getApi(request: request)
  }

  public func listApis(request: ListApisRequest) async throws
    -> GoogleCloudApiHubV1.ListApisResponse
  {
    try await self.listApis(request: request, options: .init())
  }

  public func listApis(
    request: ListApisRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListApisResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listApisByItems(
    request: ListApisRequest
  ) -> any AsyncSequence<Api, Swift.Error> & Sendable {
    self.listApisByItems(request: request, options: .init())
  }

  /// List API resources in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListApis")
  public func listApisByItems(
    request: ListApisRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Api, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListApisResponse in
      var request = request
      request.pageToken = token
      return try await self.listApis(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listApisByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Api, Swift.Error> & Sendable {
    let request = ListApisRequest().with {
      $0.parent = parent
    }
    return self.listApisByItems(request: request)
  }

  public func updateApi(request: UpdateApiRequest) async throws -> GoogleCloudApiHubV1.Api {
    try await self.updateApi(request: request, options: .init())
  }

  public func updateApi(
    request: UpdateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Api {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApi(
    api: Api?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Api {
    let request = UpdateApiRequest().with {
      $0.api = api
      $0.updateMask = updateMask
    }
    return try await self.updateApi(request: request)
  }

  public func deleteApi(request: DeleteApiRequest) async throws {
    try await self.deleteApi(request: request, options: .init())
  }

  public func deleteApi(
    request: DeleteApiRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApi(
    name: Swift.String,
  ) async throws {
    let request = DeleteApiRequest().with {
      $0.name = name
    }
    try await self.deleteApi(request: request)
  }

  public func createVersion(request: CreateVersionRequest) async throws
    -> GoogleCloudApiHubV1.Version
  {
    try await self.createVersion(request: request, options: .init())
  }

  public func createVersion(
    request: CreateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Version {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createVersion(
    parent: Swift.String,
    version: Version?,
    versionId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Version {
    let request = CreateVersionRequest().with {
      $0.parent = parent
      $0.version = version
      $0.versionId = versionId
    }
    return try await self.createVersion(request: request)
  }

  public func getVersion(request: GetVersionRequest) async throws -> GoogleCloudApiHubV1.Version {
    try await self.getVersion(request: request, options: .init())
  }

  public func getVersion(
    request: GetVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Version {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Version {
    let request = GetVersionRequest().with {
      $0.name = name
    }
    return try await self.getVersion(request: request)
  }

  public func listVersions(request: ListVersionsRequest) async throws
    -> GoogleCloudApiHubV1.ListVersionsResponse
  {
    try await self.listVersions(request: request, options: .init())
  }

  public func listVersions(
    request: ListVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listVersionsByItems(
    request: ListVersionsRequest
  ) -> any AsyncSequence<Version, Swift.Error> & Sendable {
    self.listVersionsByItems(request: request, options: .init())
  }

  /// List API versions of an API resource in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListVersions")
  public func listVersionsByItems(
    request: ListVersionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Version, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListVersionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVersionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Version, Swift.Error> & Sendable {
    let request = ListVersionsRequest().with {
      $0.parent = parent
    }
    return self.listVersionsByItems(request: request)
  }

  public func updateVersion(request: UpdateVersionRequest) async throws
    -> GoogleCloudApiHubV1.Version
  {
    try await self.updateVersion(request: request, options: .init())
  }

  public func updateVersion(
    request: UpdateVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Version {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateVersion(
    version: Version?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Version {
    let request = UpdateVersionRequest().with {
      $0.version = version
      $0.updateMask = updateMask
    }
    return try await self.updateVersion(request: request)
  }

  public func deleteVersion(request: DeleteVersionRequest) async throws {
    try await self.deleteVersion(request: request, options: .init())
  }

  public func deleteVersion(
    request: DeleteVersionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteVersion(
    name: Swift.String,
  ) async throws {
    let request = DeleteVersionRequest().with {
      $0.name = name
    }
    try await self.deleteVersion(request: request)
  }

  public func createSpec(request: CreateSpecRequest) async throws -> GoogleCloudApiHubV1.Spec {
    try await self.createSpec(request: request, options: .init())
  }

  public func createSpec(
    request: CreateSpecRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Spec {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createSpec(
    parent: Swift.String,
    spec: Spec?,
    specId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Spec {
    let request = CreateSpecRequest().with {
      $0.parent = parent
      $0.spec = spec
      $0.specId = specId
    }
    return try await self.createSpec(request: request)
  }

  public func getSpec(request: GetSpecRequest) async throws -> GoogleCloudApiHubV1.Spec {
    try await self.getSpec(request: request, options: .init())
  }

  public func getSpec(
    request: GetSpecRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Spec {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSpec(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Spec {
    let request = GetSpecRequest().with {
      $0.name = name
    }
    return try await self.getSpec(request: request)
  }

  public func getSpecContents(request: GetSpecContentsRequest) async throws
    -> GoogleCloudApiHubV1.SpecContents
  {
    try await self.getSpecContents(request: request, options: .init())
  }

  public func getSpecContents(
    request: GetSpecContentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.SpecContents {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSpecContents(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.SpecContents {
    let request = GetSpecContentsRequest().with {
      $0.name = name
    }
    return try await self.getSpecContents(request: request)
  }

  public func listSpecs(request: ListSpecsRequest) async throws
    -> GoogleCloudApiHubV1.ListSpecsResponse
  {
    try await self.listSpecs(request: request, options: .init())
  }

  public func listSpecs(
    request: ListSpecsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListSpecsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listSpecsByItems(
    request: ListSpecsRequest
  ) -> any AsyncSequence<Spec, Swift.Error> & Sendable {
    self.listSpecsByItems(request: request, options: .init())
  }

  /// List specs corresponding to a particular API resource.
  ///
  /// @Snippet(path: "ApiHub_ListSpecs")
  public func listSpecsByItems(
    request: ListSpecsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Spec, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListSpecsResponse in
      var request = request
      request.pageToken = token
      return try await self.listSpecs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSpecsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Spec, Swift.Error> & Sendable {
    let request = ListSpecsRequest().with {
      $0.parent = parent
    }
    return self.listSpecsByItems(request: request)
  }

  public func updateSpec(request: UpdateSpecRequest) async throws -> GoogleCloudApiHubV1.Spec {
    try await self.updateSpec(request: request, options: .init())
  }

  public func updateSpec(
    request: UpdateSpecRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Spec {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateSpec(
    spec: Spec?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Spec {
    let request = UpdateSpecRequest().with {
      $0.spec = spec
      $0.updateMask = updateMask
    }
    return try await self.updateSpec(request: request)
  }

  public func deleteSpec(request: DeleteSpecRequest) async throws {
    try await self.deleteSpec(request: request, options: .init())
  }

  public func deleteSpec(
    request: DeleteSpecRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteSpec(
    name: Swift.String,
  ) async throws {
    let request = DeleteSpecRequest().with {
      $0.name = name
    }
    try await self.deleteSpec(request: request)
  }

  public func createApiOperation(request: CreateApiOperationRequest) async throws
    -> GoogleCloudApiHubV1.ApiOperation
  {
    try await self.createApiOperation(request: request, options: .init())
  }

  public func createApiOperation(
    request: CreateApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApiOperation(
    parent: Swift.String,
    apiOperation: ApiOperation?,
    apiOperationId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    let request = CreateApiOperationRequest().with {
      $0.parent = parent
      $0.apiOperation = apiOperation
      $0.apiOperationId = apiOperationId
    }
    return try await self.createApiOperation(request: request)
  }

  public func getApiOperation(request: GetApiOperationRequest) async throws
    -> GoogleCloudApiHubV1.ApiOperation
  {
    try await self.getApiOperation(request: request, options: .init())
  }

  public func getApiOperation(
    request: GetApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getApiOperation(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    let request = GetApiOperationRequest().with {
      $0.name = name
    }
    return try await self.getApiOperation(request: request)
  }

  public func listApiOperations(request: ListApiOperationsRequest) async throws
    -> GoogleCloudApiHubV1.ListApiOperationsResponse
  {
    try await self.listApiOperations(request: request, options: .init())
  }

  public func listApiOperations(
    request: ListApiOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListApiOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listApiOperationsByItems(
    request: ListApiOperationsRequest
  ) -> any AsyncSequence<ApiOperation, Swift.Error> & Sendable {
    self.listApiOperationsByItems(request: request, options: .init())
  }

  /// List operations in an API version.
  ///
  /// @Snippet(path: "ApiHub_ListApiOperations")
  public func listApiOperationsByItems(
    request: ListApiOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ApiOperation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListApiOperationsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listApiOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listApiOperationsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<ApiOperation, Swift.Error> & Sendable {
    let request = ListApiOperationsRequest().with {
      $0.parent = parent
    }
    return self.listApiOperationsByItems(request: request)
  }

  public func updateApiOperation(request: UpdateApiOperationRequest) async throws
    -> GoogleCloudApiHubV1.ApiOperation
  {
    try await self.updateApiOperation(request: request, options: .init())
  }

  public func updateApiOperation(
    request: UpdateApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApiOperation(
    apiOperation: ApiOperation?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.ApiOperation {
    let request = UpdateApiOperationRequest().with {
      $0.apiOperation = apiOperation
      $0.updateMask = updateMask
    }
    return try await self.updateApiOperation(request: request)
  }

  public func deleteApiOperation(request: DeleteApiOperationRequest) async throws {
    try await self.deleteApiOperation(request: request, options: .init())
  }

  public func deleteApiOperation(
    request: DeleteApiOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApiOperation(
    name: Swift.String,
  ) async throws {
    let request = DeleteApiOperationRequest().with {
      $0.name = name
    }
    try await self.deleteApiOperation(request: request)
  }

  public func getDefinition(request: GetDefinitionRequest) async throws
    -> GoogleCloudApiHubV1.Definition
  {
    try await self.getDefinition(request: request, options: .init())
  }

  public func getDefinition(
    request: GetDefinitionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Definition {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDefinition(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Definition {
    let request = GetDefinitionRequest().with {
      $0.name = name
    }
    return try await self.getDefinition(request: request)
  }

  public func createDeployment(request: CreateDeploymentRequest) async throws
    -> GoogleCloudApiHubV1.Deployment
  {
    try await self.createDeployment(request: request, options: .init())
  }

  public func createDeployment(
    request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createDeployment(
    parent: Swift.String,
    deployment: Deployment?,
    deploymentId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    let request = CreateDeploymentRequest().with {
      $0.parent = parent
      $0.deployment = deployment
      $0.deploymentId = deploymentId
    }
    return try await self.createDeployment(request: request)
  }

  public func getDeployment(request: GetDeploymentRequest) async throws
    -> GoogleCloudApiHubV1.Deployment
  {
    try await self.getDeployment(request: request, options: .init())
  }

  public func getDeployment(
    request: GetDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    let request = GetDeploymentRequest().with {
      $0.name = name
    }
    return try await self.getDeployment(request: request)
  }

  public func listDeployments(request: ListDeploymentsRequest) async throws
    -> GoogleCloudApiHubV1.ListDeploymentsResponse
  {
    try await self.listDeployments(request: request, options: .init())
  }

  public func listDeployments(
    request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListDeploymentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listDeploymentsByItems(
    request: ListDeploymentsRequest
  ) -> any AsyncSequence<Deployment, Swift.Error> & Sendable {
    self.listDeploymentsByItems(request: request, options: .init())
  }

  /// List deployment resources in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListDeployments")
  public func listDeploymentsByItems(
    request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Deployment, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListDeploymentsResponse in
      var request = request
      request.pageToken = token
      return try await self.listDeployments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDeploymentsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Deployment, Swift.Error> & Sendable {
    let request = ListDeploymentsRequest().with {
      $0.parent = parent
    }
    return self.listDeploymentsByItems(request: request)
  }

  public func updateDeployment(request: UpdateDeploymentRequest) async throws
    -> GoogleCloudApiHubV1.Deployment
  {
    try await self.updateDeployment(request: request, options: .init())
  }

  public func updateDeployment(
    request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateDeployment(
    deployment: Deployment?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Deployment {
    let request = UpdateDeploymentRequest().with {
      $0.deployment = deployment
      $0.updateMask = updateMask
    }
    return try await self.updateDeployment(request: request)
  }

  public func deleteDeployment(request: DeleteDeploymentRequest) async throws {
    try await self.deleteDeployment(request: request, options: .init())
  }

  public func deleteDeployment(
    request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteDeployment(
    name: Swift.String,
  ) async throws {
    let request = DeleteDeploymentRequest().with {
      $0.name = name
    }
    try await self.deleteDeployment(request: request)
  }

  public func createAttribute(request: CreateAttributeRequest) async throws
    -> GoogleCloudApiHubV1.Attribute
  {
    try await self.createAttribute(request: request, options: .init())
  }

  public func createAttribute(
    request: CreateAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAttribute(
    parent: Swift.String,
    attribute: Attribute?,
    attributeId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    let request = CreateAttributeRequest().with {
      $0.parent = parent
      $0.attribute = attribute
      $0.attributeId = attributeId
    }
    return try await self.createAttribute(request: request)
  }

  public func getAttribute(request: GetAttributeRequest) async throws
    -> GoogleCloudApiHubV1.Attribute
  {
    try await self.getAttribute(request: request, options: .init())
  }

  public func getAttribute(
    request: GetAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAttribute(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    let request = GetAttributeRequest().with {
      $0.name = name
    }
    return try await self.getAttribute(request: request)
  }

  public func updateAttribute(request: UpdateAttributeRequest) async throws
    -> GoogleCloudApiHubV1.Attribute
  {
    try await self.updateAttribute(request: request, options: .init())
  }

  public func updateAttribute(
    request: UpdateAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAttribute(
    attribute: Attribute?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.Attribute {
    let request = UpdateAttributeRequest().with {
      $0.attribute = attribute
      $0.updateMask = updateMask
    }
    return try await self.updateAttribute(request: request)
  }

  public func deleteAttribute(request: DeleteAttributeRequest) async throws {
    try await self.deleteAttribute(request: request, options: .init())
  }

  public func deleteAttribute(
    request: DeleteAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAttribute(
    name: Swift.String,
  ) async throws {
    let request = DeleteAttributeRequest().with {
      $0.name = name
    }
    try await self.deleteAttribute(request: request)
  }

  public func listAttributes(request: ListAttributesRequest) async throws
    -> GoogleCloudApiHubV1.ListAttributesResponse
  {
    try await self.listAttributes(request: request, options: .init())
  }

  public func listAttributes(
    request: ListAttributesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListAttributesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAttributesByItems(
    request: ListAttributesRequest
  ) -> any AsyncSequence<Attribute, Swift.Error> & Sendable {
    self.listAttributesByItems(request: request, options: .init())
  }

  /// List all attributes.
  ///
  /// @Snippet(path: "ApiHub_ListAttributes")
  public func listAttributesByItems(
    request: ListAttributesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Attribute, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListAttributesResponse in
      var request = request
      request.pageToken = token
      return try await self.listAttributes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAttributesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Attribute, Swift.Error> & Sendable {
    let request = ListAttributesRequest().with {
      $0.parent = parent
    }
    return self.listAttributesByItems(request: request)
  }

  public func searchResources(request: SearchResourcesRequest) async throws
    -> GoogleCloudApiHubV1.SearchResourcesResponse
  {
    try await self.searchResources(request: request, options: .init())
  }

  public func searchResources(
    request: SearchResourcesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.SearchResourcesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchResourcesByItems(
    request: SearchResourcesRequest
  ) -> any AsyncSequence<SearchResult, Swift.Error> & Sendable {
    self.searchResourcesByItems(request: request, options: .init())
  }

  /// Search across API-Hub resources.
  ///
  /// @Snippet(path: "ApiHub_SearchResources")
  public func searchResourcesByItems(
    request: SearchResourcesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<SearchResult, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.SearchResourcesResponse in
      var request = request
      request.pageToken = token
      return try await self.searchResources(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchResourcesByItems(
    location: Swift.String,
    query: Swift.String,
  ) -> any AsyncSequence<SearchResult, Swift.Error> & Sendable {
    let request = SearchResourcesRequest().with {
      $0.location = location
      $0.query = query
    }
    return self.searchResourcesByItems(request: request)
  }

  public func createExternalApi(request: CreateExternalApiRequest) async throws
    -> GoogleCloudApiHubV1.ExternalApi
  {
    try await self.createExternalApi(request: request, options: .init())
  }

  public func createExternalApi(
    request: CreateExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createExternalApi(
    parent: Swift.String,
    externalApi: ExternalApi?,
    externalApiId: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    let request = CreateExternalApiRequest().with {
      $0.parent = parent
      $0.externalApi = externalApi
      $0.externalApiId = externalApiId
    }
    return try await self.createExternalApi(request: request)
  }

  public func getExternalApi(request: GetExternalApiRequest) async throws
    -> GoogleCloudApiHubV1.ExternalApi
  {
    try await self.getExternalApi(request: request, options: .init())
  }

  public func getExternalApi(
    request: GetExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getExternalApi(
    name: Swift.String,
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    let request = GetExternalApiRequest().with {
      $0.name = name
    }
    return try await self.getExternalApi(request: request)
  }

  public func updateExternalApi(request: UpdateExternalApiRequest) async throws
    -> GoogleCloudApiHubV1.ExternalApi
  {
    try await self.updateExternalApi(request: request, options: .init())
  }

  public func updateExternalApi(
    request: UpdateExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateExternalApi(
    externalApi: ExternalApi?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudApiHubV1.ExternalApi {
    let request = UpdateExternalApiRequest().with {
      $0.externalApi = externalApi
      $0.updateMask = updateMask
    }
    return try await self.updateExternalApi(request: request)
  }

  public func deleteExternalApi(request: DeleteExternalApiRequest) async throws {
    try await self.deleteExternalApi(request: request, options: .init())
  }

  public func deleteExternalApi(
    request: DeleteExternalApiRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteExternalApi(
    name: Swift.String,
  ) async throws {
    let request = DeleteExternalApiRequest().with {
      $0.name = name
    }
    try await self.deleteExternalApi(request: request)
  }

  public func listExternalApis(request: ListExternalApisRequest) async throws
    -> GoogleCloudApiHubV1.ListExternalApisResponse
  {
    try await self.listExternalApis(request: request, options: .init())
  }

  public func listExternalApis(
    request: ListExternalApisRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiHubV1.ListExternalApisResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listExternalApisByItems(
    request: ListExternalApisRequest
  ) -> any AsyncSequence<ExternalApi, Swift.Error> & Sendable {
    self.listExternalApisByItems(request: request, options: .init())
  }

  /// List External API resources in the API hub.
  ///
  /// @Snippet(path: "ApiHub_ListExternalApis")
  public func listExternalApisByItems(
    request: ListExternalApisRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ExternalApi, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiHubV1.ListExternalApisResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listExternalApis(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listExternalApisByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<ExternalApi, Swift.Error> & Sendable {
    let request = ListExternalApisRequest().with {
      $0.parent = parent
    }
    return self.listExternalApisByItems(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ApiHub_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiHub_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
