// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ApiHubRetry: ApiHubStub {
    let inner: any ApiHubStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ApiHubStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createApi(
      request: CreateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Api {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateApiRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudApiHubV1.Api
          in
          return try await self.inner.createApi(request: r, options: o)
        })
    }

    public func getApi(
      request: GetApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Api {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetApiRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudApiHubV1.Api
          in
          return try await self.inner.getApi(request: r, options: o)
        })
    }

    public func listApis(
      request: ListApisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListApisResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListApisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListApisResponse
          in
          return try await self.inner.listApis(request: r, options: o)
        })
    }

    public func updateApi(
      request: UpdateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Api {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApiRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudApiHubV1.Api
          in
          return try await self.inner.updateApi(request: r, options: o)
        })
    }

    public func deleteApi(
      request: DeleteApiRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteApiRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteApi(request: r, options: o)
        })
    }

    public func createVersion(
      request: CreateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Version {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Version
          in
          return try await self.inner.createVersion(request: r, options: o)
        })
    }

    public func getVersion(
      request: GetVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Version {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Version
          in
          return try await self.inner.getVersion(request: r, options: o)
        })
    }

    public func listVersions(
      request: ListVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListVersionsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListVersionsResponse
          in
          return try await self.inner.listVersions(request: r, options: o)
        })
    }

    public func updateVersion(
      request: UpdateVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Version {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Version
          in
          return try await self.inner.updateVersion(request: r, options: o)
        })
    }

    public func deleteVersion(
      request: DeleteVersionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteVersionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteVersion(request: r, options: o)
        })
    }

    public func createSpec(
      request: CreateSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Spec {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSpecRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Spec
          in
          return try await self.inner.createSpec(request: r, options: o)
        })
    }

    public func getSpec(
      request: GetSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Spec {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSpecRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudApiHubV1.Spec
          in
          return try await self.inner.getSpec(request: r, options: o)
        })
    }

    public func getSpecContents(
      request: GetSpecContentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.SpecContents {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSpecContentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.SpecContents
          in
          return try await self.inner.getSpecContents(request: r, options: o)
        })
    }

    public func listSpecs(
      request: ListSpecsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListSpecsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSpecsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListSpecsResponse
          in
          return try await self.inner.listSpecs(request: r, options: o)
        })
    }

    public func updateSpec(
      request: UpdateSpecRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Spec {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSpecRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Spec
          in
          return try await self.inner.updateSpec(request: r, options: o)
        })
    }

    public func deleteSpec(
      request: DeleteSpecRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteSpecRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSpec(request: r, options: o)
        })
    }

    public func createApiOperation(
      request: CreateApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ApiOperation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateApiOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ApiOperation
          in
          return try await self.inner.createApiOperation(request: r, options: o)
        })
    }

    public func getApiOperation(
      request: GetApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ApiOperation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetApiOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ApiOperation
          in
          return try await self.inner.getApiOperation(request: r, options: o)
        })
    }

    public func listApiOperations(
      request: ListApiOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListApiOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListApiOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListApiOperationsResponse
          in
          return try await self.inner.listApiOperations(request: r, options: o)
        })
    }

    public func updateApiOperation(
      request: UpdateApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ApiOperation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateApiOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ApiOperation
          in
          return try await self.inner.updateApiOperation(request: r, options: o)
        })
    }

    public func deleteApiOperation(
      request: DeleteApiOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteApiOperationRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteApiOperation(request: r, options: o)
        })
    }

    public func getDefinition(
      request: GetDefinitionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Definition {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDefinitionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Definition
          in
          return try await self.inner.getDefinition(request: r, options: o)
        })
    }

    public func createDeployment(
      request: CreateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Deployment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Deployment
          in
          return try await self.inner.createDeployment(request: r, options: o)
        })
    }

    public func getDeployment(
      request: GetDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Deployment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Deployment
          in
          return try await self.inner.getDeployment(request: r, options: o)
        })
    }

    public func listDeployments(
      request: ListDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListDeploymentsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDeploymentsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListDeploymentsResponse
          in
          return try await self.inner.listDeployments(request: r, options: o)
        })
    }

    public func updateDeployment(
      request: UpdateDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Deployment {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDeploymentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Deployment
          in
          return try await self.inner.updateDeployment(request: r, options: o)
        })
    }

    public func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteDeploymentRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDeployment(request: r, options: o)
        })
    }

    public func createAttribute(
      request: CreateAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Attribute {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAttributeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Attribute
          in
          return try await self.inner.createAttribute(request: r, options: o)
        })
    }

    public func getAttribute(
      request: GetAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Attribute {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAttributeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Attribute
          in
          return try await self.inner.getAttribute(request: r, options: o)
        })
    }

    public func updateAttribute(
      request: UpdateAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.Attribute {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAttributeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.Attribute
          in
          return try await self.inner.updateAttribute(request: r, options: o)
        })
    }

    public func deleteAttribute(
      request: DeleteAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteAttributeRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAttribute(request: r, options: o)
        })
    }

    public func listAttributes(
      request: ListAttributesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListAttributesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAttributesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListAttributesResponse
          in
          return try await self.inner.listAttributes(request: r, options: o)
        })
    }

    public func searchResources(
      request: SearchResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.SearchResourcesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SearchResourcesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.SearchResourcesResponse
          in
          return try await self.inner.searchResources(request: r, options: o)
        })
    }

    public func createExternalApi(
      request: CreateExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ExternalApi {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateExternalApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ExternalApi
          in
          return try await self.inner.createExternalApi(request: r, options: o)
        })
    }

    public func getExternalApi(
      request: GetExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ExternalApi {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetExternalApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ExternalApi
          in
          return try await self.inner.getExternalApi(request: r, options: o)
        })
    }

    public func updateExternalApi(
      request: UpdateExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ExternalApi {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateExternalApiRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ExternalApi
          in
          return try await self.inner.updateExternalApi(request: r, options: o)
        })
    }

    public func deleteExternalApi(
      request: DeleteExternalApiRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteExternalApiRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteExternalApi(request: r, options: o)
        })
    }

    public func listExternalApis(
      request: ListExternalApisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiHubV1.ListExternalApisResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListExternalApisRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudApiHubV1.ListExternalApisResponse
          in
          return try await self.inner.listExternalApis(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
