// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An attribute in the API Hub.
/// An attribute is a name value pair which can be attached to different
/// resources in the API hub based on the scope of the attribute. Attributes can
/// either be pre-defined by the API Hub or created by users.
public struct Attribute: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the attribute in the API Hub.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/attributes/{attribute}`
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the attribute.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the attribute.
  public var description: Swift.String = Swift.String()

  /// Output only. The definition type of the attribute.
  public var definitionType: Attribute.DefinitionType = Attribute.DefinitionType()

  /// Required. The scope of the attribute. It represents the resource in the API
  /// Hub to which the attribute can be linked.
  public var scope: Attribute.Scope = Attribute.Scope()

  /// Required. The type of the data of the attribute.
  public var dataType: Attribute.DataType = Attribute.DataType()

  /// Optional. The list of allowed values when the attribute value is of type
  /// enum. This is required when the data_type of the attribute is ENUM. The
  /// maximum number of allowed values of an attribute will be 1000.
  public var allowedValues: [Attribute.AllowedValue] = []

  /// Optional. The maximum number of values that the attribute can have when
  /// associated with an API Hub resource. Cardinality 1 would represent a
  /// single-valued attribute. It must not be less than 1 or greater than 20. If
  /// not specified, the cardinality would be set to 1 by default and represent a
  /// single-valued attribute.
  public var cardinality: Swift.Int32 = Swift.Int32()

  /// Output only. When mandatory is true, the attribute is mandatory for the
  /// resource specified in the scope. Only System defined attributes can be
  /// mandatory.
  public var mandatory: Swift.Bool = Swift.Bool()

  /// Output only. The time at which the attribute was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the attribute was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Attribute`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attribute().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let definitionType = CodingKeys(stringValue: "definitionType")
    static let scope = CodingKeys(stringValue: "scope")
    static let dataType = CodingKeys(stringValue: "dataType")
    static let allowedValues = CodingKeys(stringValue: "allowedValues")
    static let cardinality = CodingKeys(stringValue: "cardinality")
    static let mandatory = CodingKeys(stringValue: "mandatory")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "definitionType",
      "scope",
      "dataType",
      "allowedValues",
      "cardinality",
      "mandatory",
      "createTime",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(
      Attribute.DefinitionType.self, forKey: .definitionType)
    {
      self.definitionType = value
    }
    if let value = try container.decodeIfPresent(Attribute.Scope.self, forKey: .scope) {
      self.scope = value
    }
    if let value = try container.decodeIfPresent(Attribute.DataType.self, forKey: .dataType) {
      self.dataType = value
    }
    if let value = try container.decodeIfPresent(
      [Attribute.AllowedValue].self, forKey: .allowedValues)
    {
      self.allowedValues = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .cardinality) {
      self.cardinality = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .mandatory) {
      self.mandatory = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.definitionType, forKey: .definitionType)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.dataType, forKey: .dataType)
    try container.encode(self.allowedValues, forKey: .allowedValues)
    try container.encode(self.cardinality, forKey: .cardinality)
    try container.encode(self.mandatory, forKey: .mandatory)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The value that can be assigned to the attribute when the data type is
  /// enum.
  public struct AllowedValue: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The ID of the allowed value.
    /// * If provided, the same will be used. The service will throw an error if
    /// the specified id is already used by another allowed value in the same
    /// attribute resource.
    /// * If not provided, a system generated id derived from the display name
    /// will be used. In this case, the service will handle conflict resolution
    /// by adding a system generated suffix in case of duplicates.
    ///
    /// This value should be 4-63 characters, and valid characters
    /// are /[a-z][0-9]-/.
    public var id: Swift.String = Swift.String()

    /// Required. The display name of the allowed value.
    public var displayName: Swift.String = Swift.String()

    /// Optional. The detailed description of the allowed value.
    public var description: Swift.String = Swift.String()

    /// Optional. When set to true, the allowed value cannot be updated or
    /// deleted by the user. It can only be true for System defined attributes.
    public var immutable: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AllowedValue`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AllowedValue().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let displayName = CodingKeys(stringValue: "displayName")
      static let description = CodingKeys(stringValue: "description")
      static let immutable = CodingKeys(stringValue: "immutable")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "displayName",
        "description",
        "immutable",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .immutable) {
        self.immutable = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.immutable, forKey: .immutable)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.Attribute.AllowedValue"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Enumeration of attribute definition types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DefinitionType: Codable, Equatable, Sendable {
    /// Attribute definition type unspecified.
    case unspecified
    /// The attribute is predefined by the API Hub. Note that only the list of
    /// allowed values can be updated in this case via UpdateAttribute method.
    case systemDefined
    /// The attribute is defined by the user.
    case userDefined
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .systemDefined: return 1
      case .userDefined: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DEFINITION_TYPE_UNSPECIFIED"
      case .systemDefined: return "SYSTEM_DEFINED"
      case .userDefined: return "USER_DEFINED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DefinitionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEFINITION_TYPE_UNSPECIFIED": self = .unspecified
      case "SYSTEM_DEFINED": self = .systemDefined
      case "USER_DEFINED": self = .userDefined
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DefinitionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .systemDefined
      case 2: self = .userDefined
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DEFINITION_TYPE_UNSPECIFIED")
      case .systemDefined: return try container.encode("SYSTEM_DEFINED")
      case .userDefined: return try container.encode("USER_DEFINED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Enumeration for the scope of the attribute representing the resource in the
  /// API Hub to which the attribute can be linked.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Scope: Codable, Equatable, Sendable {
    /// Scope Unspecified.
    case unspecified
    /// Attribute can be linked to an API.
    case api
    /// Attribute can be linked to an API version.
    case version
    /// Attribute can be linked to a Spec.
    case spec
    /// Attribute can be linked to an API Operation.
    case apiOperation
    /// Attribute can be linked to a Deployment.
    case deployment
    /// Attribute can be linked to a Dependency.
    case dependency
    /// Attribute can be linked to a definition.
    case definition
    /// Attribute can be linked to a ExternalAPI.
    case externalApi
    /// Attribute can be linked to a Plugin.
    case plugin
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .api: return 1
      case .version: return 2
      case .spec: return 3
      case .apiOperation: return 4
      case .deployment: return 5
      case .dependency: return 6
      case .definition: return 7
      case .externalApi: return 8
      case .plugin: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SCOPE_UNSPECIFIED"
      case .api: return "API"
      case .version: return "VERSION"
      case .spec: return "SPEC"
      case .apiOperation: return "API_OPERATION"
      case .deployment: return "DEPLOYMENT"
      case .dependency: return "DEPENDENCY"
      case .definition: return "DEFINITION"
      case .externalApi: return "EXTERNAL_API"
      case .plugin: return "PLUGIN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Scope/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SCOPE_UNSPECIFIED": self = .unspecified
      case "API": self = .api
      case "VERSION": self = .version
      case "SPEC": self = .spec
      case "API_OPERATION": self = .apiOperation
      case "DEPLOYMENT": self = .deployment
      case "DEPENDENCY": self = .dependency
      case "DEFINITION": self = .definition
      case "EXTERNAL_API": self = .externalApi
      case "PLUGIN": self = .plugin
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Scope/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .api
      case 2: self = .version
      case 3: self = .spec
      case 4: self = .apiOperation
      case 5: self = .deployment
      case 6: self = .dependency
      case 7: self = .definition
      case 8: self = .externalApi
      case 9: self = .plugin
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SCOPE_UNSPECIFIED")
      case .api: return try container.encode("API")
      case .version: return try container.encode("VERSION")
      case .spec: return try container.encode("SPEC")
      case .apiOperation: return try container.encode("API_OPERATION")
      case .deployment: return try container.encode("DEPLOYMENT")
      case .dependency: return try container.encode("DEPENDENCY")
      case .definition: return try container.encode("DEFINITION")
      case .externalApi: return try container.encode("EXTERNAL_API")
      case .plugin: return try container.encode("PLUGIN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Enumeration of attribute's data type.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DataType: Codable, Equatable, Sendable {
    /// Attribute data type unspecified.
    case unspecified
    /// Attribute's value is of type enum.
    case `enum`
    /// Attribute's value is of type json.
    case json
    /// Attribute's value is of type string.
    case string
    /// Attribute's value is of type uri.
    case uri
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`enum`: return 1
      case .json: return 2
      case .string: return 3
      case .uri: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATA_TYPE_UNSPECIFIED"
      case .`enum`: return "ENUM"
      case .json: return "JSON"
      case .string: return "STRING"
      case .uri: return "URI"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATA_TYPE_UNSPECIFIED": self = .unspecified
      case "ENUM": self = .`enum`
      case "JSON": self = .json
      case "STRING": self = .string
      case "URI": self = .uri
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`enum`
      case 2: self = .json
      case 3: self = .string
      case 4: self = .uri
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DATA_TYPE_UNSPECIFIED")
      case .`enum`: return try container.encode("ENUM")
      case .json: return try container.encode("JSON")
      case .string: return try container.encode("STRING")
      case .uri: return try container.encode("URI")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Attribute"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
