// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AuthConfig represents the authentication information.
public struct AuthConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The authentication type.
  public var authType: AuthType = AuthType()

  /// Supported auth types.
  public var config: OneOf_Config? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuthConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthConfig().with { $0.googleServiceAccountConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let googleServiceAccountConfig = CodingKeys(stringValue: "googleServiceAccountConfig")
    static let userPasswordConfig = CodingKeys(stringValue: "userPasswordConfig")
    static let apiKeyConfig = CodingKeys(stringValue: "apiKeyConfig")
    static let oauth2ClientCredentialsConfig = CodingKeys(
      stringValue: "oauth2ClientCredentialsConfig")
    static let authType = CodingKeys(stringValue: "authType")

    static let _knownKeys: Set<Swift.String> = [
      "googleServiceAccountConfig",
      "userPasswordConfig",
      "apiKeyConfig",
      "oauth2ClientCredentialsConfig",
      "authType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AuthType.self, forKey: .authType) {
      self.authType = value
    }

    var config: OneOf_Config? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let googleServiceAccountConfig = try container.decodeIfPresent(
      GoogleServiceAccountConfig?.self, forKey: .googleServiceAccountConfig)
    {
      try configCheckAndSet(.googleServiceAccountConfig(googleServiceAccountConfig))
    }
    if let userPasswordConfig = try container.decodeIfPresent(
      AuthConfig.UserPasswordConfig?.self, forKey: .userPasswordConfig)
    {
      try configCheckAndSet(.userPasswordConfig(userPasswordConfig))
    }
    if let apiKeyConfig = try container.decodeIfPresent(
      AuthConfig.ApiKeyConfig?.self, forKey: .apiKeyConfig)
    {
      try configCheckAndSet(.apiKeyConfig(apiKeyConfig))
    }
    if let oauth2ClientCredentialsConfig = try container.decodeIfPresent(
      AuthConfig.Oauth2ClientCredentialsConfig?.self, forKey: .oauth2ClientCredentialsConfig)
    {
      try configCheckAndSet(.oauth2ClientCredentialsConfig(oauth2ClientCredentialsConfig))
    }
    self.config = config
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.authType, forKey: .authType)

    if let choice = self.config {
      switch choice {
      case .googleServiceAccountConfig(let value):
        try container.encode(value, forKey: .googleServiceAccountConfig)
      case .userPasswordConfig(let value):
        try container.encode(value, forKey: .userPasswordConfig)
      case .apiKeyConfig(let value):
        try container.encode(value, forKey: .apiKeyConfig)
      case .oauth2ClientCredentialsConfig(let value):
        try container.encode(value, forKey: .oauth2ClientCredentialsConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Parameters to support Username and Password Authentication.
  public struct UserPasswordConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Username.
    public var username: Swift.String = Swift.String()

    /// Required. Secret version reference containing the password.
    /// The `secretmanager.versions.access` permission should be
    /// granted to the service account accessing the secret.
    public var password: Secret? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UserPasswordConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserPasswordConfig().with { $0.username = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let username = CodingKeys(stringValue: "username")
      static let password = CodingKeys(stringValue: "password")

      static let _knownKeys: Set<Swift.String> = [
        "username",
        "password",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
        self.username = value
      }
      self.password = try container.decodeIfPresent(Secret.self, forKey: .password)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.username, forKey: .username)
      try container.encodeIfPresent(self.password, forKey: .password)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.AuthConfig.UserPasswordConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support Oauth 2.0 client credentials grant authentication.
  /// See https://tools.ietf.org/html/rfc6749#section-1.3.4 for more details.
  public struct Oauth2ClientCredentialsConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The client identifier.
    public var clientId: Swift.String = Swift.String()

    /// Required. Secret version reference containing the client secret.
    /// The `secretmanager.versions.access` permission should be
    /// granted to the service account accessing the secret.
    public var clientSecret: Secret? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Oauth2ClientCredentialsConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2ClientCredentialsConfig().with { $0.clientId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientId = CodingKeys(stringValue: "clientId")
      static let clientSecret = CodingKeys(stringValue: "clientSecret")

      static let _knownKeys: Set<Swift.String> = [
        "clientId",
        "clientSecret",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
        self.clientId = value
      }
      self.clientSecret = try container.decodeIfPresent(Secret.self, forKey: .clientSecret)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clientId, forKey: .clientId)
      try container.encodeIfPresent(self.clientSecret, forKey: .clientSecret)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.AuthConfig.Oauth2ClientCredentialsConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Config for authentication with API key.
  public struct ApiKeyConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The parameter name of the API key.
    /// E.g. If the API request is "https://example.com/act?api_key=<API KEY>",
    /// "api_key" would be the parameter name.
    public var name: Swift.String = Swift.String()

    /// Required. The name of the SecretManager secret version resource storing
    /// the API key. Format:
    /// `projects/{project}/secrets/{secrete}/versions/{version}`. The
    /// `secretmanager.versions.access` permission should be granted to the
    /// service account accessing the secret.
    public var apiKey: Secret? = nil

    /// Required. The location of the API key.
    /// The default value is QUERY.
    public var httpElementLocation: AuthConfig.ApiKeyConfig.HttpElementLocation = AuthConfig
      .ApiKeyConfig.HttpElementLocation()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ApiKeyConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ApiKeyConfig().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let apiKey = CodingKeys(stringValue: "apiKey")
      static let httpElementLocation = CodingKeys(stringValue: "httpElementLocation")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "apiKey",
        "httpElementLocation",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      self.apiKey = try container.decodeIfPresent(Secret.self, forKey: .apiKey)
      if let value = try container.decodeIfPresent(
        AuthConfig.ApiKeyConfig.HttpElementLocation.self, forKey: .httpElementLocation)
      {
        self.httpElementLocation = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encodeIfPresent(self.apiKey, forKey: .apiKey)
      try container.encode(self.httpElementLocation, forKey: .httpElementLocation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Enum of location an HTTP element can be.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum HttpElementLocation: Codable, Equatable, Hashable, Sendable {
      /// HTTP element location not specified.
      case unspecified
      /// Element is in the HTTP request query.
      case query
      /// Element is in the HTTP request header.
      case header
      /// Element is in the HTTP request path.
      case path
      /// Element is in the HTTP request body.
      case body
      /// Element is in the HTTP request cookie.
      case cookie
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .query: return 1
        case .header: return 2
        case .path: return 3
        case .body: return 4
        case .cookie: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "HTTP_ELEMENT_LOCATION_UNSPECIFIED"
        case .query: return "QUERY"
        case .header: return "HEADER"
        case .path: return "PATH"
        case .body: return "BODY"
        case .cookie: return "COOKIE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HttpElementLocation/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "HTTP_ELEMENT_LOCATION_UNSPECIFIED": self = .unspecified
        case "QUERY": self = .query
        case "HEADER": self = .header
        case "PATH": self = .path
        case "BODY": self = .body
        case "COOKIE": self = .cookie
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HttpElementLocation/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .query
        case 2: self = .header
        case 3: self = .path
        case 4: self = .body
        case 5: self = .cookie
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("HTTP_ELEMENT_LOCATION_UNSPECIFIED")
        case .query: return try container.encode("QUERY")
        case .header: return try container.encode("HEADER")
        case .path: return try container.encode("PATH")
        case .body: return try container.encode("BODY")
        case .cookie: return try container.encode("COOKIE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.AuthConfig.ApiKeyConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Supported auth types.
  public enum OneOf_Config: Codable, Equatable, Sendable {
    /// Google Service Account.
    indirect case googleServiceAccountConfig(GoogleServiceAccountConfig?)
    /// User Password.
    indirect case userPasswordConfig(AuthConfig.UserPasswordConfig?)
    /// Api Key Config.
    indirect case apiKeyConfig(AuthConfig.ApiKeyConfig?)
    /// Oauth2.0 Client Credentials.
    indirect case oauth2ClientCredentialsConfig(AuthConfig.Oauth2ClientCredentialsConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.AuthConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
