// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The CollectApiData method's request.
public struct CollectApiDataRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The regional location of the API hub instance and its resources.
  /// Format: `projects/{project}/locations/{location}`
  public var location: Swift.String = Swift.String()

  /// Required. The type of collection. Applies to all entries in
  /// [api_data][google.cloud.apihub.v1.CollectApiDataRequest.api_data].
  ///
  /// [google.cloud.apihub.v1.CollectApiDataRequest.api_data]: <doc:CollectApiDataRequest/apiData>
  public var collectionType: CollectionType = CollectionType()

  /// Required. The plugin instance collecting the API data.
  /// Format:
  /// `projects/{project}/locations/{location}/plugins/{plugin}/instances/{instance}`.
  public var pluginInstance: Swift.String = Swift.String()

  /// Required. The action ID to be used for collecting the API data.
  /// This should map to one of the action IDs specified
  /// in action configs in the plugin.
  public var actionId: Swift.String = Swift.String()

  /// Required. The API data to be collected.
  public var apiData: ApiData? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CollectApiDataRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CollectApiDataRequest().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let location = CodingKeys(stringValue: "location")
    static let collectionType = CodingKeys(stringValue: "collectionType")
    static let pluginInstance = CodingKeys(stringValue: "pluginInstance")
    static let actionId = CodingKeys(stringValue: "actionId")
    static let apiData = CodingKeys(stringValue: "apiData")

    static let _knownKeys: Set<Swift.String> = [
      "location",
      "collectionType",
      "pluginInstance",
      "actionId",
      "apiData",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(CollectionType.self, forKey: .collectionType) {
      self.collectionType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pluginInstance) {
      self.pluginInstance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .actionId) {
      self.actionId = value
    }
    self.apiData = try container.decodeIfPresent(ApiData.self, forKey: .apiData)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.collectionType, forKey: .collectionType)
    try container.encode(self.pluginInstance, forKey: .pluginInstance)
    try container.encode(self.actionId, forKey: .actionId)
    try container.encodeIfPresent(self.apiData, forKey: .apiData)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.CollectApiDataRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
