// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A dependency resource defined in the API hub describes a dependency directed
/// from a consumer to a supplier entity. A dependency can be defined between two
/// [Operations][google.cloud.apihub.v1.ApiOperation] or between
/// an [Operation][google.cloud.apihub.v1.ApiOperation] and [External
/// API][google.cloud.apihub.v1.ExternalApi].
///
/// [google.cloud.apihub.v1.ApiOperation]: <doc:ApiOperation>
/// [google.cloud.apihub.v1.ExternalApi]: <doc:ExternalApi>
public struct Dependency: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the dependency in the API Hub.
  ///
  /// Format: `projects/{project}/locations/{location}/dependencies/{dependency}`
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The entity acting as the consumer in the dependency.
  public var consumer: DependencyEntityReference? = nil

  /// Required. Immutable. The entity acting as the supplier in the dependency.
  public var supplier: DependencyEntityReference? = nil

  /// Output only. State of the dependency.
  public var state: Dependency.State = Dependency.State()

  /// Optional. Human readable description corresponding of the dependency.
  public var description: Swift.String = Swift.String()

  /// Output only. Discovery mode of the dependency.
  public var discoveryMode: Dependency.DiscoveryMode = Dependency.DiscoveryMode()

  /// Output only. Error details of a dependency if the system has detected it
  /// internally.
  public var errorDetail: DependencyErrorDetail? = nil

  /// Output only. The time at which the dependency was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the dependency was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The list of user defined attributes associated with the
  /// dependency resource. The key is the attribute name. It will be of the
  /// format: `projects/{project}/locations/{location}/attributes/{attribute}`.
  /// The value is the attribute values associated with the resource.
  public var attributes: [Swift.String: AttributeValues] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Dependency`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Dependency().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let consumer = CodingKeys(stringValue: "consumer")
    static let supplier = CodingKeys(stringValue: "supplier")
    static let state = CodingKeys(stringValue: "state")
    static let description = CodingKeys(stringValue: "description")
    static let discoveryMode = CodingKeys(stringValue: "discoveryMode")
    static let errorDetail = CodingKeys(stringValue: "errorDetail")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let attributes = CodingKeys(stringValue: "attributes")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "consumer",
      "supplier",
      "state",
      "description",
      "discoveryMode",
      "errorDetail",
      "createTime",
      "updateTime",
      "attributes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.consumer = try container.decodeIfPresent(DependencyEntityReference.self, forKey: .consumer)
    self.supplier = try container.decodeIfPresent(DependencyEntityReference.self, forKey: .supplier)
    if let value = try container.decodeIfPresent(Dependency.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(
      Dependency.DiscoveryMode.self, forKey: .discoveryMode)
    {
      self.discoveryMode = value
    }
    self.errorDetail = try container.decodeIfPresent(
      DependencyErrorDetail.self, forKey: .errorDetail)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: AttributeValues].self, forKey: .attributes)
    {
      self.attributes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.consumer, forKey: .consumer)
    try container.encodeIfPresent(self.supplier, forKey: .supplier)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.discoveryMode, forKey: .discoveryMode)
    try container.encodeIfPresent(self.errorDetail, forKey: .errorDetail)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.attributes, forKey: .attributes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible states for a dependency.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Dependency will be in a proposed state when it is newly identified by the
    /// API hub on its own.
    case proposed
    /// Dependency will be in a validated state when it is validated by the
    /// admin or manually created in the API hub.
    case validated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .proposed: return 1
      case .validated: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .proposed: return "PROPOSED"
      case .validated: return "VALIDATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROPOSED": self = .proposed
      case "VALIDATED": self = .validated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .proposed
      case 2: self = .validated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .proposed: return try container.encode("PROPOSED")
      case .validated: return try container.encode("VALIDATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible modes of discovering the dependency.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DiscoveryMode: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Manual mode of discovery when the dependency is defined by the user.
    case manual
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .manual: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISCOVERY_MODE_UNSPECIFIED"
      case .manual: return "MANUAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiscoveryMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISCOVERY_MODE_UNSPECIFIED": self = .unspecified
      case "MANUAL": self = .manual
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiscoveryMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .manual
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISCOVERY_MODE_UNSPECIFIED")
      case .manual: return try container.encode("MANUAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Dependency"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
