// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DiscoveredApiOperation represents an API Operation observed in one of the
/// sources.
public struct DiscoveredApiOperation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the discovered API Operation.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/discoveredApiObservations/{discovered_api_observation}/discoveredApiOperations/{discovered_api_operation}`
  public var name: Swift.String = Swift.String()

  /// Optional. First seen time stamp
  public var firstSeenTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Last seen time stamp
  public var lastSeenTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The number of occurrences of this API Operation.
  public var count: Swift.Int64 = Swift.Int64()

  /// Output only. The classification of the discovered API operation.
  public var classification: DiscoveredApiOperation.Classification =
    DiscoveredApiOperation.Classification()

  /// Output only. The list of matched results for the discovered API operation.
  /// This will be populated only if the classification is known. The current
  /// usecase is for a single match. Keeping it repeated to support multiple
  /// matches in future.
  public var matchResults: [DiscoveredApiOperation.MatchResult] = []

  /// Output only. The metadata of the source from which the api operation was
  /// collected.
  public var sourceMetadata: SourceMetadata? = nil

  /// Output only. Create time stamp of the discovered API operation in API Hub.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Update time stamp of the discovered API operation in API Hub.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// ApiOperation protocol style
  public var operation: OneOf_Operation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoveredApiOperation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveredApiOperation().with { $0.httpOperation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let httpOperation = CodingKeys(stringValue: "httpOperation")
    static let name = CodingKeys(stringValue: "name")
    static let firstSeenTime = CodingKeys(stringValue: "firstSeenTime")
    static let lastSeenTime = CodingKeys(stringValue: "lastSeenTime")
    static let count = CodingKeys(stringValue: "count")
    static let classification = CodingKeys(stringValue: "classification")
    static let matchResults = CodingKeys(stringValue: "matchResults")
    static let sourceMetadata = CodingKeys(stringValue: "sourceMetadata")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "httpOperation",
      "name",
      "firstSeenTime",
      "lastSeenTime",
      "count",
      "classification",
      "matchResults",
      "sourceMetadata",
      "createTime",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.firstSeenTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .firstSeenTime)
    self.lastSeenTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastSeenTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .count) {
      self.count = value
    }
    if let value = try container.decodeIfPresent(
      DiscoveredApiOperation.Classification.self, forKey: .classification)
    {
      self.classification = value
    }
    if let value = try container.decodeIfPresent(
      [DiscoveredApiOperation.MatchResult].self, forKey: .matchResults)
    {
      self.matchResults = value
    }
    self.sourceMetadata = try container.decodeIfPresent(
      SourceMetadata.self, forKey: .sourceMetadata)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)

    var operation: OneOf_Operation? = nil
    let operationCheckAndSet = {
      if operation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'operation'"))
      }
      operation = $0
    }
    if let httpOperation = try container.decodeIfPresent(
      HttpOperationDetails?.self, forKey: .httpOperation)
    {
      try operationCheckAndSet(.httpOperation(httpOperation))
    }
    self.operation = operation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.firstSeenTime, forKey: .firstSeenTime)
    try container.encodeIfPresent(self.lastSeenTime, forKey: .lastSeenTime)
    try container.encode(self.count, forKey: .count)
    try container.encode(self.classification, forKey: .classification)
    try container.encode(self.matchResults, forKey: .matchResults)
    try container.encodeIfPresent(self.sourceMetadata, forKey: .sourceMetadata)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)

    if let choice = self.operation {
      switch choice {
      case .httpOperation(let value):
        try container.encode(value, forKey: .httpOperation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// MatchResult represents the result of matching a discovered API operation
  /// with a catalog API operation.
  public struct MatchResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The name of the matched API Operation.
    ///
    /// Format:
    /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}/operations/{operation}`
    public var name: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MatchResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MatchResult().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")

      static let _knownKeys: Set<Swift.String> = [
        "name"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.DiscoveredApiOperation.MatchResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The classification of the discovered API operation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Classification: Codable, Equatable, Hashable, Sendable {
    /// Operation is not classified as known or unknown.
    case unspecified
    /// Operation has a matched catalog operation.
    case known
    /// Operation does not have a matched catalog operation.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .known: return 1
      case .unknown: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLASSIFICATION_UNSPECIFIED"
      case .known: return "KNOWN"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Classification/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLASSIFICATION_UNSPECIFIED": self = .unspecified
      case "KNOWN": self = .known
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Classification/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .known
      case 2: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLASSIFICATION_UNSPECIFIED")
      case .known: return try container.encode("KNOWN")
      case .unknown: return try container.encode("UNKNOWN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// ApiOperation protocol style
  public enum OneOf_Operation: Codable, Equatable, Sendable {
    /// Optional. An HTTP Operation.
    indirect case httpOperation(HttpOperationDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.DiscoveredApiOperation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
