// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Enum for the gateway type.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum GatewayType: Codable, Equatable, Hashable, Sendable {
  /// The gateway type is not specified.
  case unspecified
  /// The gateway type is Apigee X and Hybrid.
  case apigeeXAndHybrid
  /// The gateway type is Apigee Edge Public Cloud.
  case apigeeEdgePublicCloud
  /// The gateway type is Apigee Edge Private Cloud.
  case apigeeEdgePrivateCloud
  /// The gateway type is Cloud API Gateway.
  case cloudApiGateway
  /// The gateway type is Cloud Endpoints.
  case cloudEndpoints
  /// The gateway type is API Discovery.
  case apiDiscovery
  /// The gateway type for any other types of gateways.
  case others
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .apigeeXAndHybrid: return 1
    case .apigeeEdgePublicCloud: return 2
    case .apigeeEdgePrivateCloud: return 3
    case .cloudApiGateway: return 4
    case .cloudEndpoints: return 5
    case .apiDiscovery: return 6
    case .others: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "GATEWAY_TYPE_UNSPECIFIED"
    case .apigeeXAndHybrid: return "APIGEE_X_AND_HYBRID"
    case .apigeeEdgePublicCloud: return "APIGEE_EDGE_PUBLIC_CLOUD"
    case .apigeeEdgePrivateCloud: return "APIGEE_EDGE_PRIVATE_CLOUD"
    case .cloudApiGateway: return "CLOUD_API_GATEWAY"
    case .cloudEndpoints: return "CLOUD_ENDPOINTS"
    case .apiDiscovery: return "API_DISCOVERY"
    case .others: return "OTHERS"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GatewayType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "GATEWAY_TYPE_UNSPECIFIED": self = .unspecified
    case "APIGEE_X_AND_HYBRID": self = .apigeeXAndHybrid
    case "APIGEE_EDGE_PUBLIC_CLOUD": self = .apigeeEdgePublicCloud
    case "APIGEE_EDGE_PRIVATE_CLOUD": self = .apigeeEdgePrivateCloud
    case "CLOUD_API_GATEWAY": self = .cloudApiGateway
    case "CLOUD_ENDPOINTS": self = .cloudEndpoints
    case "API_DISCOVERY": self = .apiDiscovery
    case "OTHERS": self = .others
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GatewayType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .apigeeXAndHybrid
    case 2: self = .apigeeEdgePublicCloud
    case 3: self = .apigeeEdgePrivateCloud
    case 4: self = .cloudApiGateway
    case 5: self = .cloudEndpoints
    case 6: self = .apiDiscovery
    case 7: self = .others
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("GATEWAY_TYPE_UNSPECIFIED")
    case .apigeeXAndHybrid: return try container.encode("APIGEE_X_AND_HYBRID")
    case .apigeeEdgePublicCloud: return try container.encode("APIGEE_EDGE_PUBLIC_CLOUD")
    case .apigeeEdgePrivateCloud: return try container.encode("APIGEE_EDGE_PRIVATE_CLOUD")
    case .cloudApiGateway: return try container.encode("CLOUD_API_GATEWAY")
    case .cloudEndpoints: return try container.encode("CLOUD_ENDPOINTS")
    case .apiDiscovery: return try container.encode("API_DISCOVERY")
    case .others: return try container.encode("OTHERS")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
