// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Issue contains the details of a single issue found by the linter.
public struct Issue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Rule code unique to each rule defined in linter.
  public var code: Swift.String = Swift.String()

  /// Required. An array of strings indicating the location in the analyzed
  /// document where the rule was triggered.
  public var path: [Swift.String] = []

  /// Required. Human-readable message describing the issue found by the linter.
  public var message: Swift.String = Swift.String()

  /// Required. Severity level of the rule violation.
  public var severity: Severity = Severity()

  /// Required. Object describing where in the file the issue was found.
  public var range: Range? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Issue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Issue().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let code = CodingKeys(stringValue: "code")
    static let path = CodingKeys(stringValue: "path")
    static let message = CodingKeys(stringValue: "message")
    static let severity = CodingKeys(stringValue: "severity")
    static let range = CodingKeys(stringValue: "range")

    static let _knownKeys: Set<Swift.String> = [
      "code",
      "path",
      "message",
      "severity",
      "range",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .code) {
      self.code = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    if let value = try container.decodeIfPresent(Severity.self, forKey: .severity) {
      self.severity = value
    }
    self.range = try container.decodeIfPresent(Range.self, forKey: .range)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.code, forKey: .code)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.message, forKey: .message)
    try container.encode(self.severity, forKey: .severity)
    try container.encodeIfPresent(self.range, forKey: .range)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.Issue"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
