// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The [ListApiOperations][google.cloud.apihub.v1.ApiHub.ListApiOperations]
/// method's request.
///
/// [google.cloud.apihub.v1.ApiHub.ListApiOperations]: <doc:ApiHubClient/listApiOperations(request:options:)>
public struct ListApiOperationsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent which owns this collection of operations i.e., the API
  /// version. Format:
  /// `projects/{project}/locations/{location}/apis/{api}/versions/{version}`
  public var parent: Swift.String = Swift.String()

  /// Optional. An expression that filters the list of ApiOperations.
  ///
  /// A filter expression consists of a field name, a comparison
  /// operator, and a value for filtering. The value must be a string or a
  /// boolean. The comparison operator must be one of: `<`, `>` or
  /// `=`. Filters are not case sensitive.
  ///
  /// The following fields in the `ApiOperation` are eligible for filtering:
  ///   * `name` - The ApiOperation resource name. Allowed comparison
  ///   operators:
  ///   `=`.
  ///   * `details.http_operation.path.path` - The http operation's complete path
  ///   relative to server endpoint. Allowed comparison operators: `=`.
  ///   * `details.http_operation.method` - The http operation method type.
  ///   Allowed comparison operators: `=`.
  ///   * `details.deprecated` - Indicates if the ApiOperation is deprecated.
  ///   Allowed values are True / False indicating the deprycation status of the
  ///   ApiOperation. Allowed comparison operators: `=`.
  ///   * `create_time` - The time at which the ApiOperation was created. The
  ///   value should be in the (RFC3339)[https://tools.ietf.org/html/rfc3339]
  ///   format. Allowed comparison operators: `>` and `<`.
  ///   * `attributes.projects/test-project-id/locations/test-location-id/
  ///   attributes/user-defined-attribute-id.enum_values.values.id` - The
  ///   allowed value id of the user defined enum attribute associated with the
  ///   Resource. Allowed comparison operator is `:`. Here
  ///   user-defined-attribute-enum-id is a placeholder that can be replaced with
  ///   any user defined enum attribute name.
  ///   * `attributes.projects/test-project-id/locations/test-location-id/
  ///   attributes/user-defined-attribute-id.enum_values.values.display_name`
  ///   - The allowed value display name of the user defined enum attribute
  ///   associated with the Resource. Allowed comparison operator is `:`. Here
  ///   user-defined-attribute-enum-display-name is a placeholder that can be
  ///   replaced with any user defined enum attribute enum name.
  ///   * `attributes.projects/test-project-id/locations/test-location-id/
  ///   attributes/user-defined-attribute-id.string_values.values` - The
  ///   allowed value of the user defined string attribute associated with the
  ///   Resource. Allowed comparison operator is `:`. Here
  ///   user-defined-attribute-string is a placeholder that can be replaced with
  ///   any user defined string attribute name.
  ///   * `attributes.projects/test-project-id/locations/test-location-id/
  ///   attributes/user-defined-attribute-id.json_values.values` - The
  ///   allowed value of the user defined JSON attribute associated with the
  ///   Resource. Allowed comparison operator is `:`. Here
  ///   user-defined-attribute-json is a placeholder that can be replaced with
  ///   any user defined JSON attribute name.
  ///
  /// Expressions are combined with either `AND` logic operator or `OR` logical
  /// operator but not both of them together i.e. only one of the `AND` or `OR`
  /// operator can be used throughout the filter string and both the operators
  /// cannot be used together. No other logical operators are supported. At most
  /// three filter fields are allowed in the filter string and if provided
  /// more than that then `INVALID_ARGUMENT` error is returned by the API.
  ///
  /// Here are a few examples:
  ///
  ///   * `details.deprecated = True` -  The ApiOperation is deprecated.
  ///   * `details.http_operation.method = GET AND create_time <
  ///   \"2021-08-15T14:50:00Z\" AND create_time > \"2021-08-10T12:00:00Z\"` -
  ///   The method of the http operation of the ApiOperation is _GET_ and the
  ///   spec was created before _2021-08-15 14:50:00 UTC_ and after _2021-08-10
  ///   12:00:00 UTC_.
  ///   * `details.http_operation.method = GET OR details.http_operation.method =
  ///   POST`. - The http operation of the method of ApiOperation is _GET_ or
  ///   _POST_.
  ///   * `details.deprecated = True AND
  ///   attributes.projects/test-project-id/locations/test-location-id/
  ///   attributes/17650f90-4a29-4971-b3c0-d5532da3764b.string_values.values:
  ///   test`  - The filter string specifies that the ApiOperation is deprecated
  ///   and the value of the user defined attribute of type string is _test_.
  public var filter: Swift.String = Swift.String()

  /// Optional. The maximum number of operations to return. The service may
  /// return fewer than this value. If unspecified, at most 50 operations will be
  /// returned. The maximum value is 1000; values above 1000 will be coerced to
  /// 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous `ListApiOperations` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters (except page_size) provided to
  /// `ListApiOperations` must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListApiOperationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListApiOperationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let filter = CodingKeys(stringValue: "filter")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "filter",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.ListApiOperationsRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
