// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// SourceMetadata represents the metadata for a resource at the source.
public struct SourceMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The type of the source.
  public var sourceType: SourceMetadata.SourceType = SourceMetadata.SourceType()

  /// Output only. The unique identifier of the resource at the source.
  public var originalResourceId: Swift.String = Swift.String()

  /// Output only. The time at which the resource was created at the source.
  public var originalResourceCreateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the resource was last updated at the source.
  public var originalResourceUpdateTime: GoogleWKT.WKTTimestamp? = nil

  /// The source of the resource.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SourceMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceMetadata().with { $0.pluginInstanceActionSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pluginInstanceActionSource = CodingKeys(stringValue: "pluginInstanceActionSource")
    static let sourceType = CodingKeys(stringValue: "sourceType")
    static let originalResourceId = CodingKeys(stringValue: "originalResourceId")
    static let originalResourceCreateTime = CodingKeys(stringValue: "originalResourceCreateTime")
    static let originalResourceUpdateTime = CodingKeys(stringValue: "originalResourceUpdateTime")

    static let _knownKeys: Set<Swift.String> = [
      "pluginInstanceActionSource",
      "sourceType",
      "originalResourceId",
      "originalResourceCreateTime",
      "originalResourceUpdateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      SourceMetadata.SourceType.self, forKey: .sourceType)
    {
      self.sourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .originalResourceId) {
      self.originalResourceId = value
    }
    self.originalResourceCreateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .originalResourceCreateTime)
    self.originalResourceUpdateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .originalResourceUpdateTime)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let pluginInstanceActionSource = try container.decodeIfPresent(
      SourceMetadata.PluginInstanceActionSource?.self, forKey: .pluginInstanceActionSource)
    {
      try sourceCheckAndSet(.pluginInstanceActionSource(pluginInstanceActionSource))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceType, forKey: .sourceType)
    try container.encode(self.originalResourceId, forKey: .originalResourceId)
    try container.encodeIfPresent(
      self.originalResourceCreateTime, forKey: .originalResourceCreateTime)
    try container.encodeIfPresent(
      self.originalResourceUpdateTime, forKey: .originalResourceUpdateTime)

    if let choice = self.source {
      switch choice {
      case .pluginInstanceActionSource(let value):
        try container.encode(value, forKey: .pluginInstanceActionSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// PluginInstanceActionSource represents the plugin instance action source.
  public struct PluginInstanceActionSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The resource name of the source plugin instance.
    /// Format is
    /// `projects/{project}/locations/{location}/plugins/{plugin}/instances/{instance}`
    public var pluginInstance: Swift.String = Swift.String()

    /// Output only. The id of the plugin instance action.
    public var actionId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PluginInstanceActionSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PluginInstanceActionSource().with { $0.pluginInstance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pluginInstance = CodingKeys(stringValue: "pluginInstance")
      static let actionId = CodingKeys(stringValue: "actionId")

      static let _knownKeys: Set<Swift.String> = [
        "pluginInstance",
        "actionId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pluginInstance) {
        self.pluginInstance = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .actionId) {
        self.actionId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.pluginInstance, forKey: .pluginInstance)
      try container.encode(self.actionId, forKey: .actionId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.apihub.v1.SourceMetadata.PluginInstanceActionSource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The possible types of the source.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SourceType: Codable, Equatable, Hashable, Sendable {
    /// Source type not specified.
    case unspecified
    /// Source type plugin.
    case plugin
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .plugin: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SOURCE_TYPE_UNSPECIFIED"
      case .plugin: return "PLUGIN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SOURCE_TYPE_UNSPECIFIED": self = .unspecified
      case "PLUGIN": self = .plugin
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .plugin
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SOURCE_TYPE_UNSPECIFIED")
      case .plugin: return try container.encode("PLUGIN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The source of the resource.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Output only. The source of the resource is a plugin instance action.
    indirect case pluginInstanceActionSource(SourceMetadata.PluginInstanceActionSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.SourceMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
