// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// SpecDetails contains the details parsed from supported
/// spec types.
public struct SpecDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The description of the spec.
  public var description: Swift.String = Swift.String()

  public var details: DetailsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SpecDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpecDetails().with { $0.openApiSpecDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let openApiSpecDetails = CodingKeys(stringValue: "openApiSpecDetails")
    static let description = CodingKeys(stringValue: "description")

    static let _knownKeys: Set<Swift.String> = [
      "openApiSpecDetails",
      "description",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }

    var details: DetailsOneOf? = nil
    let detailsCheckAndSet = {
      if details != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'details'"))
      }
      details = $0
    }
    if let openApiSpecDetails = try container.decodeIfPresent(
      OpenApiSpecDetails?.self, forKey: .openApiSpecDetails)
    {
      try detailsCheckAndSet(.openApiSpecDetails(openApiSpecDetails))
    }
    self.details = details
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)

    if let choice = self.details {
      switch choice {
      case .openApiSpecDetails(let value):
        try container.encode(value, forKey: .openApiSpecDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum DetailsOneOf: Codable, Equatable, Sendable {
    /// Output only. Additional details apart from `OperationDetails` parsed from
    /// an OpenAPI spec. The OperationDetails parsed from the spec can be
    /// obtained by using
    /// [ListAPIOperations][google.cloud.apihub.v1.ApiHub.ListApiOperations]
    /// method.
    ///
    /// [google.cloud.apihub.v1.ApiHub.ListApiOperations]: <doc:ApiHubClient/listApiOperations(request:options:)>
    indirect case openApiSpecDetails(OpenApiSpecDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apihub.v1.SpecDetails"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
